-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Versão do servidor: 10.4.32-MariaDB
-- Versão do PHP: 8.0.30

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Banco de dados: `testevocacional`
--

-- --------------------------------------------------------

--
-- Estrutura para tabela `cadastro`
--

CREATE TABLE `cadastro` (
  `id` int(11) NOT NULL,
  `nome` varchar(150) NOT NULL,
  `email` varchar(150) NOT NULL,
  `whatsapp` varchar(30) NOT NULL,
  `pontos_biologicas` int(11) DEFAULT 0,
  `pontos_exatas` int(11) DEFAULT 0,
  `pontos_humanas` int(11) DEFAULT 0,
  `pontos_tecnologicas` int(11) DEFAULT 0,
  `perfil_predominante` varchar(50) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------

--
-- Estrutura para tabela `questoes`
--

CREATE TABLE `questoes` (
  `id` int(11) NOT NULL,
  `questao` text NOT NULL,
  `opcaoA` varchar(255) NOT NULL,
  `opcaoB` varchar(255) NOT NULL,
  `opcaoC` varchar(255) NOT NULL,
  `opcaoD` varchar(255) NOT NULL,
  `imagem` varchar(255) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Despejando dados para a tabela `questoes`
--


INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (1, 'Na hora de organizar o porta-malas do carro para uma longa viagem com a família ou amigos, como você costuma agir ou o que prioriza?', 'Priorizo acomodar em local de fácil acesso a caixa térmica com alimentos frescos, bastante água, o kit de primeiros socorros/remédios e o espaço seguro para o transporte do pet.', 'Analiso a geometria do espaço: distribuo as malas mais pesadas na base para equilibrar o centro de gravidade do veículo e encaixo cada volume calculando o melhor aproveitamento do espaço útil.', 'Garanto que a bagagem de cada pessoa tenha seu lugar respeitado e deixo à mão itens que tragam conforto e bem-estar para o trajeto, como travesseiros, jogos para o grupo e lembranças da viagem.', 'Separo um compartimento para todos os adaptadores, cabos, powerbanks e suportes, checando se os dispositivos móveis e ferramentas digitais de rota estão carregados e organizados.', 'src\\img\\imagem-1788750275205.jpg', 'Mon Sep 07 2026 00:04:35 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (2, 'Você ficou responsável por organizar e comprar os comes e bebes para um encontro com amigos ou família no final de semana. Como você planeja e executa essa tarefa?', 'Foco na qualidade e procedência dos itens: seleciono opções frescas, verifico ingredientes para atender quem tem restrições alimentares (como alergias ou intolerâncias) e garanto opções saudáveis e hidratação adequada.', 'Calculo as quantidades exatas por pessoa com base na duração do evento, comparo o preço por quilo/litro entre marcas e controlo os gastos rigorosamente para que a divisão da conta seja precisa e sem desperdício.', 'Converso com o grupo para entender as preferências de cada um, priorizando pratos que tragam boas lembranças, criem uma atmosfera afetiva e façam todos se sentirem confortáveis e acolhidos.', 'Uso aplicativos para calcular o consumo, faço cotação de preços online com entrega rápida e utilizo planilhas ou apps de divisão de contas automática com Pix para facilitar a organização.', 'src\\img\\imagem-1788751090913.jpg', 'Mon Sep 07 2026 00:18:10 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (3, 'Você decidiu iniciar uma nova atividade física para manter uma rotina mais ativa no dia a dia. Ao escolher a modalidade e acompanhar sua evolução, qual é a sua principal abordagem?', 'Avalio como o exercício afeta meus músculos, respiração e postura, buscando entender a recuperação biológica do corpo, a nutrição adequada e os benefícios para a minha saúde a longo prazo.', 'Defino metas com base em números exatos: calculo calorias gastas, meço a evolução de cargas ou tempo por quilômetro e analiso tabelas de rendimento para otimizar meu progresso.', 'Priorizo modalidades que permitam interação social, trabalho em equipe ou que tragam equilíbrio mental, usando o momento da atividade para aliviar as pressões do dia e me reconectar com as pessoas.', 'Uso relógios inteligentes, sensores e aplicativos com dashboards que registram dados em tempo real, testando novos equipamentos e comparando relatórios automáticos de desempenho.', 'src/img/imagem-1788755178366.jpg', 'Mon Sep 07 2026 01:26:18 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (4, 'Você decidiu renovar e reorganizar um cômodo da sua casa (como o quarto ou a sala de estudos/trabalho). Qual aspecto você prioriza no planejamento dessa mudança?', 'Priorizo a circulação de ar natural, a entrada de luz solar, a presença de plantas e a ergonomia dos móveis, garantindo um ambiente biologicamente saudável que favoreça a respiração e a postura.', 'Tiro as medidas exatas do espaço, calculo a área de piso e parede para estimar o consumo exato de materiais sem sobras e monto uma planilha de custos para manter o projeto dentro do orçamento planejado.', 'Foco na sensação de acolhimento e identidade pessoal: escolho cores que transmitam calma, crio um espaço agradável para receber pessoas ou estudar em família e reservo um lugar para fotos e lembranças.', 'Planejo a distribuição de tomadas, cabos de rede e repetidores de sinal, integrando iluminação inteligente controlada por aplicativo e assistentes virtuais para automatizar as rotinas do cômodo.', 'src/img/imagem-1788755246082.jpg', 'Mon Sep 07 2026 01:27:26 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (5, 'Você precisa escolher um novo eletrodoméstico para a casa (como uma geladeira ou ar-condicionado). Diante de vários modelos disponíveis, em qual critério você baseia sua decisão de compra?', 'Analiso os benefícios diretos para a saúde e o ambiente: filtros antibacterianos, níveis de conservação biológica de alimentos, purificação do ar e o baixo nível de ruído para preservar a qualidade do sono.', 'Calculo a relação custo-benefício matemática: comparo o consumo de energia em kWh na conta de luz, o tempo de amortização do valor investido e as medidas milimétricas em relação ao espaço disponível.', 'Leio relatos e avaliações de outros usuários sobre a facilidade de uso no cotidiano e priorizo um design acolhedor que combine com o convívio e a harmonia das pessoas que moram na casa.', 'Priorizo modelos com recursos inteligentes: controle via aplicativo, integração com sistemas de automação residencial, sensores modernos e alertas automáticos de funcionamento e manutenção.', 'src/img/imagem-1788755481918.jpg', 'Mon Sep 07 2026 01:31:21 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (6, 'Ao planejar uma viagem ou passeio de fim de semana com amigos ou família, qual aspecto ou detalhe você costuma priorizar para garantir que tudo dê certo', 'Priorizo roteiros ao ar livre e contato com a natureza: verifico a preservação das trilhas e praias, a qualidade da água, o clima local e garanto pausas para hidratação e recuperação física do grupo.', 'Monto um cronograma financeiro exato: calculo gastos com combustível por quilômetro rodado, pedágios, estimativa de alimentação diária e mantenho uma planilha para não estourar o orçamento previsto.', 'Pesquiso a história da região, tradições culturais e costumes locais, buscando passeios que proporcionem boas conversas, pratos típicos e memórias afetivas para fortalecer os laços entre as pessoas.', 'Organizo tudo por meios digitais: comparo rotas e trânsito em tempo real por mapas virtuais, centralizo reservas em aplicativos e garanto internet móvel estável e carregadores portáteis para a rota.', 'src/img/imagem-1788782919657.jpg', 'Mon Sep 07 2026 09:08:39 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (7, 'Você decidiu cultivar algumas plantas, flores ou uma pequena horta em casa (no quintal ou na varanda). Qual é a sua principal atenção no cuidado desse cultivo?', 'Observo atentamente a fisiologia das plantas: a coloração das folhas, a exposição correta à luz solar, a drenagem do solo e o uso de adubação orgânica para prevenir pragas de forma natural.', 'Calculo com precisão as proporções de terra, areia e nutrientes para o substrato, meço o volume ideal de cada vaso e controlo o orçamento gasto com mudas e insumos.', 'Encaro o cultivo como um momento terapêutico para desacelerar da rotina, escolhendo espécies que tragam memórias afetivas e deixem o ambiente mais acolhedor para a família e amigos.', 'Instalo um sistema de irrigação por gotejamento com temporizador ou sensores de umidade no solo, buscando automatizar os cuidados e monitorar o ambiente por aplicativos.', 'src/img/imagem-1788783197226.jpg', 'Mon Sep 07 2026 09:13:17 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (8, 'Você tem uma semana intensa pela frente, com vários prazos, tarefas e compromissos para entregar. Como você estrutura sua rotina para dar conta de tudo sem se sobrecarregar?', 'Respeito os limites do meu organismo: planejo horários fixos para dormir, garanto refeições balanceadas, mantenho uma garrafa d\'água sempre por perto e faço pausas regulares para alongar a coluna e descansar a visão.', 'Distribuo as horas do dia em blocos exatos de tempo: calculo a estimativa de minutos para cada tarefa, ordeno por nível de complexidade e acompanho graficamente a taxa de entrega para não estourar nenhum prazo.', 'Converso com as pessoas envolvidas para negociar expectativas e prazos com empatia, reservando momentos para descontrair, desabafar com amigos e manter o ambiente de trabalho ou estudo colaborativo e leve.', 'Centralizo tudo em aplicativos de tarefas sincronizados em nuvem, programo lembretes automáticos no celular e utilizo ferramentas digitais ou inteligência artificial para otimizar etapas repetitivas da rotina', 'src/img/imagem-1788783461980.jpg', 'Mon Sep 07 2026 09:17:41 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (9, 'Ao organizar o descarte de materiais, embalagens e restos do cotidiano na sua casa, qual aspecto você mais prioriza para adotar uma postura sustentável?', 'Separo os resíduos orgânicos para compostagem e adubação natural, avaliando o tempo de biodegradação dos itens para evitar a contaminação do solo e dos lençóis freáticos.', 'Meço a redução de volume do lixo gerado, calculo a economia no reaproveitamento de recipientes e estimo o percentual de materiais recicláveis desviados dos aterros sanitários.', 'Higienizo e embalo os recicláveis com segurança para valorizar o trabalho dos catadores e cooperativas locais, incentivando familiares e vizinhos a adotarem o mesmo cuidado social.', 'Uso aplicativos para localizar ecopontos especializados de eletrônicos e baterias, consulto guias interativos de reciclagem e acompanho soluções de logística reversa inteligente.', 'src/img/imagem-1788785331927.jpg', 'Mon Sep 07 2026 09:48:51 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (10, 'Ao preparar um café da manhã ou um lanche reforçado antes de começar o dia, em qual detalhe você mais concentra sua atenção?', 'No equilíbrio nutricional dos alimentos: combino proteínas, fibras e frutas frescas para garantir energia duradoura, facilitar a digestão e manter o organismo funcionando bem ao longo da manhã.', 'Nas medidas e proporções precisas: peso ou meço os ingredientes com exatidão, controlo rigorosamente o tempo de fogo ou forno e calculo a porção exata para evitar desperdício de insumos.', 'No valor afetivo e acolhedor da refeição: escolho receitas que tragam conforto e boas lembranças, capricho na apresentação da mesa e aproveito o momento para conversar com quem está por perto.', 'Na praticidade dos aparelhos inteligentes: uso cafeteiras programáveis, timers digitais ou air fryer com receitas salvas para otimizar o tempo e garantir o ponto ideal sem esforço manual.', 'src/img/imagem-1788785527140.jpg', 'Mon Sep 07 2026 09:52:07 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (11, 'Ao definir como você vai se deslocar pela cidade para um compromisso diário (escola, trabalho ou curso), qual critério mais influencia sua escolha de transporte e rota?', 'Priorizo opções ativas ou ao ar livre, como caminhar ou pedalar parte do caminho, avaliando o benefício físico do exercício, a oxigenação do corpo e a menor exposição a ambientes abafados.', 'Calculo com precisão a relação custo-benefício: meço o tempo exato de percurso, comparo o valor de passagens ou consumo de combustível por quilômetro e escolho a alternativa mais econômica e pontual', 'Prefiro combinar caronas com conhecidos ou usar transporte coletivo para observar o movimento da cidade, valorizando a troca com outras pessoas e a gentileza no trânsito.', 'Consulto aplicativos de navegação em tempo real para fugir de congestionamentos, uso bilhete ou pagamento digital por aproximação e acompanho a previsão exata de chegada por satélite.', 'src/img/imagem-1788785688409.jpg', 'Mon Sep 07 2026 09:54:48 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (12, 'Você foi convidado para participar da organização de um evento voluntário ou comunitário no seu bairro. Em qual frente você prefere atuar?', 'Na triagem de arrecadação de alimentos perecíveis e medicamentos, checando condições de validade, higiene e orientações básicas de saúde preventiva.', 'No controle financeiro e orçamentário: cálculo de custos de infraestrutura, prestação de contas exata e análise quantitativa do público atendido.', 'Na recepção e atendimento direto ao público, escutando as histórias da comunidade, mediando conversas e promovendo a inclusão de todos.', 'No desenvolvimento e gestão das inscrições online, transmissão ao vivo, suporte técnico de som/rede e divulgação automatizada nas redes.', 'src/img/imagem-1788828893937.jpg', 'Mon Sep 07 2026 21:54:53 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (13, 'Ao planejar a compra de roupas ou calçados para o seu uso diário, qual critério tem mais peso na sua decisão?', 'Priorizo tecidos de fibras naturais e respiráveis, calçados com suporte anatômico/ergonômico para a coluna e itens hipoalergênicos.', 'Avalio o custo por uso (preço dividido pela durabilidade esperada), comparo porcentagens de desconto e mantenho o gasto rigorosamente dentro do orçamento.', 'Busco saber a história da marca, se há respeito aos direitos trabalhistas na confecção e priorizo peças que expressem minha identidade e cultura.', 'Prefiro peças com tecidos tecnológicos (secagem ultra-rápida, repelentes de água ou odor) e pesquiso avaliações em plataformas e comparadores digitais.', 'src/img/imagem-1788829034497.jpg', 'Mon Sep 07 2026 21:57:14 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (14, 'Você decide adotar um animal de estimação ou ajudar a cuidar do pet de um amigo. Qual é o seu foco principal nessa responsabilidade?', 'Preocupo-me com o calendário de vacinas, a qualidade biológica da ração, a saúde digestiva, o peso do animal e as visitas preventivas ao veterinário.', 'Calculo os gastos mensais com alimentação e remédios, meço as gramas exatas de ração diária por peso corporal e cronometro os horários fixos de passeio', 'Foco na adaptação emocional do animal, criando um vínculo de afeto, acolhimento e garantindo que ele se sinta seguro e parte integrante da família.', 'Utilizo coleiras inteligentes com GPS, bebedouros/comedouros automáticos programáveis e aplicativos de celular para monitorar o histórico e rotina do pet.', 'src/img/imagem-1788829247887.jpg', 'Mon Sep 07 2026 22:00:47 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (15, 'Você decide reformular seu padrão de sono e descanso noturno para render melhor durante o dia. Como você aborda isso?', 'Estudo os ciclos biológicos do sono, evito cafeína à noite, regulo a alimentação noturna e presto atenção aos níveis de relaxamento muscular do corpo.', 'Calculo o número exato de horas e ciclos de sono de 90 minutos, tabulando a média semanal para identificar variações matemáticas de energia.', 'Pratico momentos de descompressão mental com leituras reflexivas, diários ou conversas tra', 'Utilizo smartbands, relógios ou anéis inteligentes com sensores de batimentos e oxigenação para analisar gráficos automáticos de sono profundo via app.', 'src/img/imagem-1788829449670.jpg', 'Mon Sep 07 2026 22:04:09 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (16, 'Durante uma caminhada pelo seu bairro ou parque, o que mais desperta sua curiosidade e atenção?', 'A variedade de árvores, pássaros e insetos, observando como a vegetação urbana reage ao clima e à poluição da cidade.', 'A geometria dos edifícios, a velocidade média do tráfego, os cálculos de fluxo e a proporção de espaço entre calçadas e pistas.', 'O comportamento das pessoas, as interações sociais, as expressões culturais dos transeuntes e a história por trás dos pontos históricos do bairro.', 'A fiação subterrânea ou aérea, a presença de câmeras de reconhecimento, totens de recarga, painéis solares e antenas 5G espalhadas pelo local.', 'src/img/imagem-1788829771026.jpg', 'Mon Sep 07 2026 22:09:31 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (17, 'Você vai preparar uma apresentação ou trabalho para apresentar publicamente. Qual etapa você prioriza com mais entusiasmo?', 'Investigar evidências baseadas na saúde, meio ambiente ou impacto na vida cotidiana das pessoas, trazendo exemplos práticos da natureza humana.', 'Estruturar a apresentação com dados estatísticos sólidos, gráficos precisos, métricas numéricas e uma linha de raciocínio estritamente lógica.', 'Construir uma narrativa envolvente (storytelling), adaptando a linguagem para engajar emocionalmente o público e gerar empatia com a mensagem.', 'Configurar slides interativos, recursos audiovisuais modernos, ferramentas digitais de votação em tempo real e automações visuais de ponta.', 'src/img/imagem-1788830000378.jpg', 'Mon Sep 07 2026 22:13:20 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (18, 'Se você pudesse escolher um tema de documentário ou série para maratonar no fim de semana, qual escolheria?', 'A vida selvagem, os mistérios do cérebro humano, medicina preventiva ou a complexidade dos ecossistemas marinhos.', 'Enigmas da física, matemática aplicada às finanças, engenharia de megaestruturas ou astronomia quantitativa do universo.', 'Documentários sobre acontecimentos históricos, movimentos sociais, comportamento humano, biografias inspiradoras e diversidade cultural.', 'A evolução da inteligência artificial, cibernética, viagens espaciais tripuladas, robótica e inovações que moldarão o futuro digital.', 'src/img/imagem-1788830226551.jpg', 'Mon Sep 07 2026 22:17:06 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (19, 'Em uma situação de crise ou emergência que exige tomada de decisão rápida, qual é a sua postura natural?', 'Verifico imediatamente a integridade física e respiratória das pessoas, aplicando primeiros socorros ou buscando condições seguras de sobrevivência.', 'Avalio os riscos de forma fria e lógica, calculando as probabilidades de cada alternativa para escolher o caminho de menor perda estatística.', 'Busco manter o grupo calmo, prestando apoio psicológico, mediando conflitos de pânico e garantindo que ninguém se sinta desamparado.', 'Acesso canais digitais de emergência, consulto dados em tempo real via celular e utilizo ferramentas eletrônicas para solucionar o bloqueio rapidamente.  Pergunta 20', 'src/img/imagem-1788830382424.jpg', 'Mon Sep 07 2026 22:19:42 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (20, 'Ao escolher um destino de férias, o que mais atrai a sua vontade de viajar?', 'Destinos com ecoturismo preservado, parques nacionais, praias com recifes de corais e trilhas imersas em florestas nativas.', 'Cidades com roteiros detalhadamente orçados, onde posso calcular o melhor retorno financeiro para cada dia investido na viagem.', 'Lugares ricos em patrimônio histórico, museus', 'Metrópoles ultramodernas repletas de arranha-céus, cidades inteligentes, museus de ciência interativos e mobilidade 100% digital.', 'src/img/imagem-1788830594670.jpg', 'Mon Sep 07 2026 22:23:14 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (21, 'Você precisa escolher um hobby manual para praticar nas horas livres. Qual destas opções mais combina com você?', 'Jardinagem com plantas medicinais, cuidados com terrários ou apicultura urbana.', 'Jogos de xadrez avançado, aeromodelismo em escala milimétrica ou quebra-cabeças complexos de lógica.', 'Escrita criativa, pintura de retratos, clube de leitura ou teatro amador.', 'Montagem de peças de computadores, pilotagem de drones, eletrônica com placas Arduino ou impressão 3D.', 'src/img/imagem-1788830702461.jpg', 'Mon Sep 07 2026 22:25:02 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (22, 'Ao ler as notícias do dia em um portal de informações, qual manchete chama sua atenção primeiro?', 'Descobertas sobre novos tratamentos de saúde, conservação ambiental ou avanços no combate a pandemias.', 'Variação de taxas de juros, relatórios econômicos, projeções orçamentárias ou estatísticas de mercado.', 'Debates sobre direitos sociais, impactos da educação na sociedade, história das comunidades ou manifestações culturais.', 'Lançamentos de novos chips, avanços em softwares de automação, computação quântica e segurança da informação.', 'src/img/imagem-1788830918030.jpg', 'Mon Sep 07 2026 22:28:38 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (23, 'Diante de um problema com a água encanada ou infiltração em sua casa, qual aspecto você investiga primeiro?', 'Avalio se há risco de contaminação bacteriana, presença de mofo prejudicial à respiração ou acúmulo de larvas de insetos.', 'Meço a vazão pelo hidrômetro, calculo a pressão hidráulica e estimo o custo do desperdício de água no valor final da conta.', 'Converso com vizinhos ou com o condomínio para entender se o problema afeta a convivência do prédio e busco um acordo amigável.', 'Pesquiso na internet tutoriais detalhados de diagnóstico e utilizo sensores de vazamento ou ferramentas especializadas para achar a falha.', 'src/img/imagem-1788831071217.jpg', 'Mon Sep 07 2026 22:31:11 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (24, 'Se você fosse criar um projeto para melhorar a escola ou local de trabalho, qual seria a sua prioridade?', 'Melhorar a qualidade das refeições no refeitório, criar espaços verdes ao ar livre e programas de conscientização sobre saúde mental e física.', 'Otimizar a grade de horários, reestruturar a alocação do orçamento e criar métricas claras para medir o desempenho de todos.', 'Criar programas de mentoria, círculos de diálogo contra o preconceito e projetos culturais que fortaleçam os vínculos de amizade.', 'Modernizar a rede Wi-Fi, digitalizar processos manuais por meio de plataformas na nuvem e equipar salas com telas interativas.', 'src/img/imagem-1788831268036.jpg', 'Mon Sep 07 2026 22:34:28 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (25, 'Ao escolher um livro em uma livraria ou biblioteca, qual prateleira costuma te prender por mais tempo?', 'Seção de biologia geral, nutrição, neurociência, zoologia e conservação ambiental.', 'Seção de matemática pura, física teórica, estatística, economia quantitativa ou investimentos.', 'Seção de filosofia, sociologia, psicologia social, história mundial e ficção clássica.', 'Seção de ciência da computação, programação, inovação digital, inteligência artificial e engenharia de sistemas.', 'src/img/imagem-1788831439720.jpg', 'Mon Sep 07 2026 22:37:19 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (26, 'Quando você se depara com um produto com defeito que comprou recentemente, qual é o seu primeiro impulso?', 'Verifico se o material pode liberar substâncias tóxicas, se há riscos alérgicos ou perigo físico imediato a quem manuseia.', 'Calculo os prazos legais de garantia, a perda financeira e organizo todos os comprovantes e notas fiscais com precisão.', 'Tento um diálogo compreensivo e educado com o vendedor ou atendente, buscando entender o lado do prestador e negociar com empatia.', 'Abro o chamado via chat automático/bot, registro fotos do defeito no portal e busco nos fóruns da internet se é um defeito de fábrica conhecido.  Pergunta 27', 'src/img/imagem-1788831614187.jpg', 'Mon Sep 07 2026 22:40:14 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (27, 'Se você fosse chamado para organizar a biblioteca comunitária da sua região, como você classificaria as obras?', 'Dando destaque a seções práticas sobre anatomia, guias botânicos, primeiros socorros e guias de agricultura urbana e saúde.', 'Criando uma codificação numérica e decimal rigorosa, calculando índices de empréstimo e projetando rotatividade por cálculo estatístico.', 'Agrupando livros por movimentos literários e períodos históricos, criando espaços confortáveis de debate e incentivo à leitura.', 'Implementando etiquetas RFID/código de barras, catálogo 100% digital na nuvem e totens de autoatendimento para devolução.', 'src/img/imagem-1788831989927.jpg', 'Mon Sep 07 2026 22:46:29 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (28, 'Ao começar a aprender a cozinhar pratos mais elaborados, qual é o seu principal estilo na cozinha?', 'Observo como o cozimento altera as propriedades dos nutrientes, a conservação orgânica e o ponto biológico ideal de carnes e vegetais.', 'Sigo as receitas como uma fórmula matemática: balança digital para pesar cada grama, termômetro culinário e cronômetro ativado.', 'Encaro a comida como afeto e memória cultural: improviso temperos de família e cozinho pensando no prazer de reunir as pessoas.', 'Utilizo eletroportáteis modernos de precisão (sous-vide, fornos por indução ou receitas em aplicativos inteligentes com timer integrado).  Pergunta 29', 'src/img/imagem-1788832203440.jpg', 'Mon Sep 07 2026 22:50:03 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (29, 'Como você costuma gerenciar suas senhas e contas de acessos pessoais?', 'Uso autenticação por biometria (impressão digital ou leitura facial), valorizando a identidade orgânica única do meu corpo.', 'Crio combinações lógicas baseadas em fórmulas alfanuméricas estruturadas, trocando periodicamente com base em intervalos exatos de dias.', 'Escolho palavras que remetem a lembranças afetivas significativas ou nomes importantes da minha história para não esquecer.', 'Utilizo gerenciadores de senhas em nuvem com criptografia de ponta a ponta e chaves de segurança com verificação em duas etapas (2FA).', 'src/img/imagem-1788832350897.jpg', 'Mon Sep 07 2026 22:52:30 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (30, 'Se você participasse da fundação de uma nova cidade ou bairro planejado, em qual setor gostaria de opinar?', 'Na preservação dos mananciais hídricos, arborização de espécies nativas, saneamento biológico e equilíbrio da fauna local.', 'No traçado viário simétrico, dimensionamento de cargas elétricas, cálculo de vazão de águas pluviais e viabilidade orçamentária.', 'Na distribuição democrática de praças, centros culturais comunitários, escolas acessíveis e incentivo à convivência coletiva.', 'Na infraestrutura de cabeamento de alta velocidade, postes inteligentes, sensores urbanos IoT e sistemas de mobilidade autônoma.', 'src/img/imagem-1788832482295.jpg', 'Mon Sep 07 2026 22:54:42 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (31, 'Diante de uma notícia polêmica nas redes sociais sobre o futuro do trabalho, qual ângulo mais desperta sua reflexão?', 'O impacto do estresse e do excesso de telas na saúde física, ergonômica e no sistema imunológico dos trabalhadores.', 'A análise estatística de aumento de produtividade, custos corporativos e a margem de retorno sobre os postos de trabalho.', 'Os dilemas éticos da substituição do trabalho humano, a desigualdade social gerada e a perda de conexões interpessoais.', 'Quais ferramentas de software e algoritmos estão liderando essa transformação e como dominar a nova infraestrutura digital.', 'src/img/imagem-1788832604610.jpg', 'Mon Sep 07 2026 22:56:44 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (32, 'Você decidiu pintar as paredes do seu quarto ou de uma sala da sua casa. Qual aspecto você prioriza durante o planejamento e a execução do trabalho?', 'Escolho tintas ecológicas sem odor ou à base d\'água e com componentes antimofo, mantendo janelas bem abertas para garantir a qualidade do ar e a saúde respiratória durante o processo.', 'Calculo a área total das paredes em metros quadrados, desconto as aberturas de portas e janelas e estimo o rendimento exato em litros por demão para evitar desperdício e custos extras.', 'Pesquiso o significado e a psicologia das cores para selecionar tons que transmitam paz, harmonia e acolhimento para todos que compartilham o ambiente no dia a dia.', 'Utilizo pistolas elétricas de pintura pulverizada, testo simuladores virtuais de cores por realidade aumentada no celular e pesquiso tintas com tecnologia de isolamento térmico.', 'src/img/imagem-1788923600478.jpg', 'Wed Sep 09 2026 00:13:20 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (33, 'No seu tempo livre dedicado ao seu hobby predileto, qual é o principal elemento que te mantém motivado e focado nessa atividade?', 'A sensação de reequilíbrio corporal e alívio do estresse biológico, percebendo como a prática desacelera meus batimentos, descansa a mente e restaura minha disposição física.', 'A evolução lógica e matemática da prática: analisar pontuações, comparar tempos, dominar regras com precisão cirúrgica e traçar estratégias para otimizar meu rendimento.', 'A oportunidade de compartilhar o momento com amigos, participar de clubes/encontros comunitários ou produzir algo com significado afetivo e cultural para presentear pessoas queridas.', 'Explorar novos recursos digitais, configurar periféricos avançados, atualizar hardwares ou programar rotinas e mods para aperfeiçoar a experiência técnica do passatempo.', 'src/img/imagem-1788923970076.jpg', 'Wed Sep 09 2026 00:19:30 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (34, 'Você vai a um grande festival ou show de música ao vivo com apresentações de vários artistas. O que mais chama sua atenção e define sua preparação para o evento?', 'Planejo pausas para hidratação constante, escolho roupas e tênis com suporte anatômico e fico atento à alimentação adequada para aguentar horas em pé sem prejudicar o corpo.', 'Analiso o mapa do evento para calcular o tempo exato de deslocamento entre palcos, controlo os custos de transporte e consumo e cronometro os horários para ver todas as atrações sem atraso.', 'A energia do público cantando em uníssono, a mensagem das letras, a história dos movimentos musicais e a conexão emocional estabelecida entre os artistas e a multidão.', 'O espetáculo dos painéis de LED de alta definição, os efeitos visuais sincronizados por software, a engenharia da mesa de som digital e os aplicativos do festival para navegação.', 'src/img/imagem-1788924254213.jpg', 'Wed Sep 09 2026 00:24:14 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (35, 'Ao se preparar para uma prova importante, vestibular ou processo seletivo concorrido, qual é o seu principal método para absorver e fixar os conteúdos?', 'Respeito os ritmos do meu cérebro: intercalo blocos de concentração com pausas ativas para caminhar, bebo bastante água e evito noites em claro para preservar a consolidação da memória.', 'Estruturo um cronograma com metas quantitativas: resolvo bancos de exercícios calculando a porcentagem de acertos por tema e mantenho gráficos do rendimento semanal.', 'Monto grupos de estudos para debater temas em conjunto, uso a técnica de ensinar a matéria com minhas próprias palavras para os colegas e crio histórias para contextualizar os conceitos.', 'Uso aplicativos de repetição espaçada com flashcards digitais, resumo matérias usando inteligência artificial e organizo mapas mentais sincronizados na nuvem em múltiplos dispositivos.', 'src/img/imagem-1788924398872.jpg', 'Wed Sep 09 2026 00:26:38 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (36, 'Ao fazer as compras mensais de supermercado, qual hábito melhor descreve o seu comportamento no corredor e no caixa?', 'Leio com atenção a tabela nutricional e a lista de ingredientes, evitando ultraprocessados, conservantes artificiais e produtos de procedência duvidosa.', 'Comparo o valor por quilo/litro entre embalagens de tamanhos diferentes e confiro o cupom fiscal item por item para garantir que não houve cobrança incorreta.', 'Priorizo marcas que apoiam cooperativas locais ou pequenos produtores e trato os repositores e caixas com simpatia, valorizando o contato humano.', 'Utilizo aplicativos de supermercado com cupons digitais automáticos, pago por aproximação ou carteira digital e uso scanners móveis para checar preços.', 'src/img/imagem-1788948806039.jpg', 'Wed Sep 09 2026 07:13:26 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (37, 'Você precisa comprar um presente de aniversário para um amigo próximo, mas está em dúvida sobre o que escolher. Como decide?', 'Escolho algo voltado à saúde ou autocuidado, como uma cesta de chás orgânicos, óleos naturais ou um item ergonômico para a rotina dele.', 'Estipulo um orçamento limite exato e pesquiso itens cuja durabilidade e funcionalidade compensem cada centavo investido com base em comparações de preço.', 'Busco algo com significado afetivo profundo, como um álbum com memórias da amizade, uma carta sincera ou um livro marcante para a trajetória dele.', 'Presenteio com um acessório tecnológico, fones sem fio modernos, itens para o setup dele ou uma assinatura de um serviço digital inovador.', 'src/img/imagem-1788948985708.jpg', 'Wed Sep 09 2026 07:16:25 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (38, 'Em um dia livre no fim de semana, você e seus amigos decidem se reunir para jogar jogos de tabuleiro ou cartas. Qual é a sua atitude durante a partida?', 'Fico atento à postura e ao bem-estar do grupo, garantindo que o ambiente esteja arejado e que haja água e petiscos nutritivos por perto.', 'Foco na estratégia matemática: calculo probabilidades de jogadas, conto pontos mentalmente e desenvolvo táticas lógicas para vencer com eficiência.', 'Preocupo-me em garantir que todos estejam se divertindo e integrados, mediando discussões e priorizando as boas risadas acima do placar final.', 'Sugiro jogos que integrem aplicativos no celular, mecânicas digitais complementares ou componentes com design técnico e futurista.', 'src/img/imagem-1788949286260.jpg', 'Wed Sep 09 2026 07:21:26 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (39, 'Você está prestes a embarcar em uma viagem de avião que durará várias horas. Qual é o seu principal cuidado antes e durante o voo?', 'Bebo bastante água para combater o ar seco da cabine, uso roupas confortáveis e faço exercícios de circulação nas pernas para evitar fadiga corporal.', 'Calculo o peso exato da bagagem para não pagar taxas extras e cronometro os horários de check-in, raio-X e portão de embarque com antecedência precisa.', 'Observo as pessoas ao redor, converso amigavelmente com quem está próximo e reflito sobre a cultura e a história do lugar de destino.', 'Baixo previamente episódios e mídias offline no tablet, levo adaptadores e baterias portáteis e acompanho o trajeto em tempo real no mapa de voo.', 'src/img/imagem-1788949495362.jpg', 'Wed Sep 09 2026 07:24:55 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (40, 'Você notou que há sobras de alimentos e verduras quase passando do ponto na geladeira. O que faz para resolver?', 'Avalio o estado biológico dos itens para garantir frescor e crio uma receita nutritiva aproveitando talos, cascas e folhas sem perder vitaminas.', 'Analiso as porções que sobraram, calculo o rendimento de novas refeições para a semana e meço a economia gerada ao evitar qualquer tipo de desperdício.', 'reparo um prato caseiro e farto para dividir com quem mora comigo ou com vizinhos, transformando a refeição em um gesto de cuidado e acolhimento.', 'Consulto aplicativos de inteligência artificial culinária, digitando os ingredientes disponíveis para receber o passo a passo instantâneo de preparo.', 'src/img/imagem-1788949841149.jpg', 'Wed Sep 09 2026 07:30:41 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (41, 'Você comprou uma estante ou escrivaninha desmontada pela internet. Como você conduz a montagem?', 'Garanto uma boa iluminação natural, uso luvas de proteção e cuido da postura ao abaixar e levantar caixas para não forçar a lombar.', 'Separo parafusos, cavilhas e ferragens em potes numerados, conferindo item por item no manual e alinhando réguas e esquadros com exatidão.', 'Chamo amigos ou familiares para transformar a montagem em um momento descontraído de parceria, dividindo as tarefas de forma leve.', 'Busco vídeos de montagem rápida do modelo exato na internet ou uso simuladores em 3D e parafusadeiras elétricas automáticas com regulagem de torque.', 'src/img/imagem-1788950191350.jpg', 'Wed Sep 09 2026 07:36:31 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (42, 'Você decide fazer uma limpeza profunda e organização nos armários e gavetas de casa. Qual é a sua prioridade?', 'Higienizar com produtos neutros para eliminar poeira, mofo e ácaros que possam irritar as vias respiratórias e a pele da família.', 'Contar e categorizar as peças, medir o volume livre que foi ganho nas prateleiras e estimar quanto pode ser economizado ou arrecadado com desapegos.', 'Separar roupas e sapatos em bom estado para doação a quem precisa, lembrando das histórias de cada peça e compartilhando boas lembranças.', 'Organizar tudo com organizadores modulares impressos em 3D, rotulando caixas com códigos digitais ou etiquetas inteligentes no celular.', 'src/img/imagem-1788950453129.jpg', 'Wed Sep 09 2026 07:40:53 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (43, 'Ao caminhar por uma feira de artesanato ou produtos locais, o que mais desperta o seu interesse?', 'Barracas de mel puro, plantas medicinais, cosméticos orgânicos, argilas e alimentos feitos com ingredientes agroecológicos.', 'A precisão do encaixe das peças de marcenaria ou cerâmica, a durabilidade dos materiais e a relação entre custo de matéria-prima e preço de venda.', 'As conversas com os produtores, a tradição cultural transmitida por gerações e a narrativa de identidade popular presente no artesanato.', 'Objetos criados com técnicas de corte a laser, luminárias modernas de LED com circuitos aparentes ou pequenos inventos utilitários.', 'src/img/imagem-1788963672226.jpg', 'Wed Sep 09 2026 11:21:12 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (44, 'Faltou energia elétrica na sua casa e em todo o bairro durante a noite. Qual é o seu primeiro pensamento ou atitude?', 'Checo se a geladeira permanecerá fechada para não estragar alimentos perecíveis e abro as janelas para manter a ventilação e o ar fresco.', 'Calculo a autonomia das luzes de emergência disponíveis e estimo quanto tempo a bateria dos aparelhos vai durar com base no consumo mínimo.', 'Reúno todos da casa ou ligo para vizinhos idosos para garantir que estejam bem, aproveitando o momento à luz de velas para conversar sem pressa.', 'Verifico o nobreak dos equipamentos, consulto o mapa de interrupção da rede elétrica via dados móveis e configuro o celular como roteador de contingência.', 'src/img/imagem-1788965889641.jpg', 'Wed Sep 09 2026 11:58:09 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (45, 'Você resolve estabelecer o hábito de ler um livro antes de dormir. O que orienta a escolha do seu momento e formato de leitura?', 'Uso uma iluminação âmbar suave para não atrapalhar o ciclo do sono e escolho uma postura anatômica confortável para descansar o pescoço e a coluna.', 'Estabeleço uma meta de páginas diárias, calculando em quantas semanas concluirei a obra com base na minha velocidade média de leitura.', 'Escolho obras biográficas, poemas ou romances sociais que despertem empatia, reflexões sobre as relações humanas e paz de espírito.', 'Utilizo um leitor digital (e-reader) com brilho ajustável, sincronização em nuvem dos destaques e dicionário instantâneo integrado.', 'src/img/imagem-1788967646715.jpg', 'Wed Sep 09 2026 12:27:26 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (46, 'Você precisa escolher um convênio de saúde ou seguro individual/familiar. Qual critério é decisivo para você?', 'A abrangência de exames preventivos, qualidade da rede hospitalar, coberturas para nutrição, fisioterapia e foco em medicina integrativa.', 'A planilha de cálculos atuariais: valor das mensalidades, porcentagens de coparticipação, índices de reajuste e projeção do custo a longo prazo.', 'O histórico de acolhimento e humanização das clínicas e depoimentos reais de pessoas atendidas com atenção, respeito e cuidado.', 'A agilidade dos canais virtuais: pronto atendimento por telemedicina via app, liberação automática de guias com inteligência artificial e reembolso digital ágil.', 'src/img/imagem-1788970328426.jpg', 'Wed Sep 09 2026 13:12:08 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (47, 'Você precisa trocar o colchão ou os travesseiros do quarto. Em que detalhe você baseia a escolha?', 'Na densidade correta para alinhamento da coluna, em tecidos com propriedades antiácaro e na ergonomia corporal para relaxamento muscular pleno.', 'No período de garantia do fabricante, testes de durabilidade mecânica de molas e espumas e na melhor relação entre durabilidade e preço.', 'Na sensação de aconchego, no conforto emocional de um ambiente acolhedor e na satisfação de quem compartilha a cama no dia a dia.', 'm tecnologias inovadoras de memória viscoelástica, materiais com gel de dissipação térmica ativa e tecidos projetados cientificamente.', 'src/img/imagem-1788970510436.jpg', 'Wed Sep 09 2026 13:15:10 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (48, 'Em uma conversa sobre que carreira seguir, qual argumento parece mais convincente para você?', 'Escolher áreas voltadas ao alívio do sofrimento biológico, cuidados com a preservação do planeta e melhoria contínua da saúde humana e animal.', 'Basear a escolha em gráficos econômicos, taxas de empregabilidade comprovadas por estatísticas e solidez financeira com previsibilidade de carreira.', 'Dedicar-se a profissões que combatam a desigualdade social, defendam direitos fundamentais, eduquem pessoas e promovam transformação comunitária.', 'Investir em setores na fronteira da tecnologia, inteligência artificial, engenharia de sistemas e desenvolvimento de soluções digitais autônomas.', 'src/img/imagem-1788970737255.jpg', 'Wed Sep 09 2026 13:18:57 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (49, 'Ao planejar a iluminação de uma sala de estar ou bancada de estudos, qual é o seu foco?', 'Adequar a temperatura de cor da luz aos ritmos naturais do corpo para não causar estresse visual ou perturbações no sono.', 'Calcular a quantidade de lúmens necessária por metro quadrado, a potência em watts e a redução percentual calculada na conta de energia', 'Criar pontos de luz quente e indireta que tornem o ambiente receptivo, intimista e propício para receber pessoas e prosear.', 'Instalar lâmpadas inteligentes controladas por comando de voz ou aplicativo, integrando automações e perfis de cores personalizáveis.', 'src/img/imagem-1788970870321.jpg', 'Wed Sep 09 2026 13:21:10 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (50, 'Em um período de seca na sua região, qual medida doméstica você prioriza para economizar água?', 'Instalo filtros naturais para reaproveitar água em plantas e checo recipientes para evitar qualquer acúmulo de larvas e mosquitos transmissores de doenças.', 'Cronometro rigorosamente o tempo de banho, calculo a redução diária de litros consumidos e acompanho as medições do hidrômetro no papel.', 'Converso com a família e os vizinhos para criar uma conscientização comunitária e garantir que todos se ajudem sem desperdícios coletivos.', 'Pesquiso sistemas automáticos com sensores de vazamento e instalo redutores e temporizadores eletrônicos acoplados às torneiras.', 'src/img/imagem-1788971063044.jpg', 'Wed Sep 09 2026 13:24:23 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (51, 'Ao planejar a compra de uma bicicleta para uso regular, qual fator mais orienta a sua escolha?', 'O ajuste biomecânico e ergonômico ao corpo, prevenindo dores lombares e nas articulações dos joelhos.', 'A relação entre marchas, o peso do quadro em gramas e a economia direta gerada em relação ao transporte público.', 'O estilo do modelo, a integração com passeios coletivos com amigos e a sensação de liberdade ao pedalar.', 'A compatibilidade com ciclo-computadores com GPS, sensores de cadência via Bluetooth e luzes inteligentes.', 'src/img/imagem-1789008279402.jpg', '0000-00-00 00:00:00');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (52, 'Diante de uma goteira ou vazamento simples em uma torneira, como você procede?', 'Verifico se a umidade provocou proliferação de fungos ou mofo prejudiciais à qualidade do ar ambiente.', 'Calculo o volume aproximado de litros perdidos por dia e o impacto financeiro que isso terá na conta no final do mês.', 'Converso com as pessoas da residência para alinhar o conserto sem incômodo à rotina de convivência da casa.', 'Consulto diagramas técnicos digitais e vídeos especializados para entender a vedação e o mecanismo interno da peça.', 'src/img/imagem-1789008427478.jpg', '0000-00-00 00:00:00');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (53, 'Ao montar uma playlist para um momento de foco ou descanso, em que você presta atenção?', 'Na frequência sonora e no ritmo das faixas para desacelerar os batimentos cardíacos e baixar o cortisol.', 'Na duração total exata da lista para cronometrar perfeitamente o tempo do bloco de trabalho ou pausa.', 'Na profundidade poética das composições e na capacidade das músicas de evocarem lembranças afetivas.', 'Nos algoritmos de recomendação da plataforma e na configuração de equalização de áudio em alta fidelidade.', 'src/img/imagem-1789008751631.jpg', '0000-00-00 00:00:00');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (54, 'Ao escolher um café ou chá para o consumo diário, qual critério se destaca para você?', 'As propriedades antioxidantes, o nível de pureza orgânica e a forma como a cafeína afeta meu metabolismo.', 'A relação custo por xícara produzida e o rendimento comparado entre embalagens de gramaturas diferentes.', 'O ritual acolhedor de servir a bebida em momentos de pausa ou durante conversas agradáveis em família.', 'Os métodos de extração que utilizam balanças com temporizadores digitais e moedores com granulometria ajustável.', 'src/img/imagem-1789008900423.jpg', '0000-00-00 00:00:00');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (55, 'Você decide aprender um novo idioma. Qual é o seu foco principal durante o aprendizado?', 'Como o cérebro se adapta à nova linguagem e a pronúncia fisiológica correta dos sons vocálicos.', 'A estrutura gramatical lógica, o número de palavras novas dominadas por semana e tabelas de conjugação.', 'A imersão na cultura, costumes, literatura e a capacidade de fazer amizades e compreender histórias locais.', 'Aplicativos com trilhas gamificadas, assistentes virtuais de conversação e ferramentas de tradução por IA.', 'src/img/imagem-1789009097035.jpg', '0000-00-00 00:00:00');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (56, 'Em uma feira livre de frutas e legumes, o que guia sua escolha de compra?', 'O frescor evidente, a ausência de defensivos químicos e a riqueza de nutrientes das folhas e frutos.', 'O preço por quilo em cada barraca, conferindo o troco e calculando o gasto total do dia com rigor.', 'A simpatia dos feirantes tradicionais, valorizando as conversas e o trabalho dos pequenos produtores.', 'A possibilidade de pagar com carteira digital sem contato e a consulta rápida a tabelas nutricionais online.', 'src/img/imagem-1789009742588.jpg', '0000-00-00 00:00:00');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (57, 'Se você precisasse escolher um podcast para acompanhar semanalmente, qual tema escolheria?', 'Neurociência do comportamento, medicina do estilo de vida, nutrição esportiva e sustentabilidade.', 'Economia aplicada, tendências de mercado, raciocínio lógico e gestão de investimentos pessoais.', 'Entrevistas biográficas, dilemas da sociedade, antropologia cultural e história das artes.', 'Tendências de cibersegurança, computação em nuvem, inteligência artificial e arquitetura de software.', 'src/img/imagem-1789009976229.jpg', '0000-00-00 00:00:00');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (58, 'Ao planejar a compra de um smartphone novo, o que mais pesa na decisão?', 'Os índices de emissão de radiação SAR e os modos de proteção ocular para preservar a visão.', 'O comparativo analítico entre preço, tempo de vida útil projetado e depreciação financeira do aparelho.', 'A facilidade de compartilhar momentos em família e a reputação da marca quanto à ética corporativa.', 'A velocidade do processador, o tipo de memória, a taxa de atualização da tela e a autonomia do sistema operacional.', 'src/img/imagem-1789039691179.jpg', '0000-00-00 00:00:00');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (59, 'Você precisa organizar seus documentos fiscais e comprovantes pessoais. Como faz?', 'Priorizo a organização de laudos médicos, carteira de vacinação e exames laboratoriais em ordem de saúde.', 'Crio pastas indexadas rigorosamente por ano e mês, conferindo valores pagos e calculando balanços.', 'Guardo com carinho cartas antigas e registros importantes da história da minha família junto aos papéis.', 'Digitalizo tudo com OCR para arquivos PDF na nuvem, organizando com tags de busca e backup criptografado.', 'src/img/imagem-1789040026983.jpg', '0000-00-00 00:00:00');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (60, 'Durante uma viagem pela serra ou pelo campo, o que mais atrai o seu olhar?', 'A variedade de espécies arbóreas nativas, o relevo florestal e a vitalidade das nascentes de água.', 'As curvas de nível das estradas, a engenharia dos viadutos e o consumo de combustível nas subidas.', 'A arquitetura vernacular das casas de campo e o estilo de vida tradicional dos moradores do vilarejo.', 'As torres de transmissão de dados, as pás eólicas de geração de energia e as estações meteorológicas.', 'src/img/imagem-1789040255777.jpg', '0000-00-00 00:00:00');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (61, 'Diante de um dia com clima muito frio e chuvoso, como você prefere passar o tempo livre?', 'Preparando um chá de ervas quentes com propriedades calmantes e fazendo alongamentos para aquecer as articulações.', 'Organizando o orçamento do mês e planejando planilhas de despesas futuras com tranquilidade.', 'Lendo um romance envolvente ou assistindo a um filme clássico com a família debaixo das cobertas.', 'Explorando novos softwares, jogando games no computador ou ajustando automações da casa pelo celular.', 'src/img/imagem-1789040406024.jpg', '0000-00-00 00:00:00');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (62, 'Em um trabalho acadêmico ou corporativo em equipe, em qual papel você rende melhor?', 'Cuidando da ergonomia do grupo e garantindo que o cronograma não prejudique a saúde e o sono de ninguém.', 'Estruturando a metodologia quantitativa, os cálculos de amostra e a revisão lógica das métricas do projeto.', 'Facilitando a comunicação entre os membros, mediando opiniões divergentes e redigindo a introdução narrativa.', 'Cuidando da formatação técnica, dos repositórios compartilhados de arquivos e das ferramentas de apresentação.', 'src/img/imagem-1789040939590.jpg', '0000-00-00 00:00:00');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (63, 'Ao preparar uma mala para uma viagem de curta duração, como você organiza os itens?', 'Garantindo protetor solar, repelente orgânico, remédios essenciais e calçados que não machuquem os pés.', 'Calculando a quantidade exata de peças por dia de viagem para não carregar nem uma grama de peso desnecessário.', 'Escolhendo roupas que tenham significado especial para os encontros e jantares planejados com as pessoas.', 'Acomodando cabos universais, adaptadores de tomada e organizadores com proteção antichoque para eletrônicos.', 'src/img/imagem-1789041771468.jpg', '0000-00-00 00:00:00');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (64, 'Ao se deparar com uma notícia sobre uma nova descoberta científica, qual aspecto você busca conferir?', 'Se o avanço traz curas reais para enfermidades ou alternativas para a preservação de biomas ameaçados.', 'O rigor matemático das probabilidades, o tamanho da amostragem estatística e a margem de erro da pesquisa.', 'Os impactos éticos da descoberta sobre os direitos humanos e como ela transformará a vida em comunidade.', 'A tecnologia empregada nos experimentos, o poder computacional utilizado e as linguagens de modelagem.', 'src/img/imagem-1789042393973.jpg', '0000-00-00 00:00:00');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (65, 'Você precisa organizar a festa de aniversário de uma pessoa próxima. Em que detalhe você foca?', 'Em oferecer um cardápio leve, com sucos naturais e opções para quem possui intolerâncias alimentares.', 'Na planilha detalhada de custos por convidado para garantir que os gastos fiquem dentro do teto estipulado.', 'Em preparar homenagens emotivas, murais de fotos e uma recepção acolhedora para reunir quem o aniversariante ama.', 'Na montagem da iluminação de festa, na playlist sincronizada e no convite digital interativo com confirmação online.', 'src/img/imagem-1789043091118.jpg', '0000-00-00 00:00:00');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (66, 'Se você pudesse fazer um trabalho voluntário em uma reserva ecológica, qual função escolheria?', 'Acompanhar biólogos no manejo de animais silvestres resgatados e na recuperação de mudas de árvores nativas.', 'Controlar o censo populacional das espécies em planilhas e calcular o fluxo de visitantes por trilha permitida.', 'Atuar como guia comunitário, conscientizando crianças e moradores sobre o valor cultural daquela terra.', 'Operar drones de monitoramento florestal, instalar armadilhas fotográficas com sensores e registrar dados via GPS.', 'src/img/imagem-1789043337481.jpg', '0000-00-00 00:00:00');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (67, 'Ao notar que a bateria do seu celular está descarregando muito rápido, qual é a sua reação?', 'Avalio se o uso excessivo do aparelho está prejudicando a saúde dos meus olhos e decido passar mais tempo ao ar livre.', 'Calculo a porcentagem gasta por hora e verifico se vale a pena financeiramente trocar a bateria ou comprar um novo.', 'Peço o carregador emprestado a alguém próximo e aproveito para puxar assunto e bater um papo.', 'Abro as configurações do sistema para analisar os processos em segundo plano e fechar serviços que consomem recursos.', 'src/img/imagem-1789043437086.jpg', '0000-00-00 00:00:00');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (68, 'Ao entrar em um museu com diversas exposições, para onde você se direciona primeiro?', 'Para a ala de história natural, fósseis, evolução das espécies e espécimes botânicos preservados.', 'Para a seção de instrumentos científicos antigos, astrolábios e réplicas de engrenagens de precisão.', 'Para a galeria de retratos históricos, manifestações de arte popular e objetos do cotidiano dos povos ancestrais.', 'Para os pavilhões interativos de robótica, realidade virtual e simulações digitais do espaço.', 'src/img/imagem-1789043568527.jpg', '0000-00-00 00:00:00');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (69, 'Se você precisasse escolher um instrumento musical para aprender, o que motivaria sua escolha?', 'Instrumentos de sopro, prestando atenção no controle da respiração diafragmática e na postura pulmonar.', 'O piano ou teclado, pela estrutura lógica das partituras, compassos matemáticos e intervalos precisos.', 'O violão ou canto popular, para acompanhar cantorias em volta da mesa e criar momentos afetivos com amigos.', 'Sintetizadores eletrônicos e mesas controladoras MIDI com interfaces ligadas a softwares de produção musical.', 'src/img/imagem-1789043684037.jpg', '0000-00-00 00:00:00');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (70, 'Ao decidir fazer uma faxina geral no computador ou celular, qual critério orienta sua organização?', 'Excluo arquivos com calma para criar um ambiente de trabalho digital que reduza a ansiedade e a sobrecarga mental.', 'Analiso o espaço livre em gigabytes antes e depois da limpeza, calculando a porcentagem de armazenamento liberado.', 'Reorganizo e revejo álbuns de fotos de viagens e mensagens antigas trocadas com pessoas queridas.', 'Rodo scripts ou ferramentas de limpeza de cache, organizo pastas de código e atualizo repositórios de sistema.', 'src/img/imagem-1789043750770.jpg', '0000-00-00 00:00:00');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (71, 'Diante da escolha de um restaurante para comemorar uma conquista, o que te faz bater o martelo?', 'A procedência dos ingredientes, optando por pratos com alimentos frescos, leves e preparo artesanal.', 'O preço médio das opções no cardápio comparado às porções servidas, garantindo excelente custo-benefício.', 'A atmosfera intimista, o atendimento acolhedor dos garçons e o espaço aconchegante para longas conversas.', 'A conveniência de fazer reservas pelo aplicativo com pagamento integrado e cardápio interativo via QR code.', 'src/img/imagem-1789043960346.jpg', '0000-00-00 00:00:00');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (72, 'Ao organizar a sua mesa de trabalho ou bancada de estudos diários, qual detalhe é indispensável?', 'A altura correta da cadeira para proteger os punhos e a lombar, além de uma planta pequena para purificar o ar.', 'O alinhamento milimétrico de réguas, canetas e calculadoras dentro de suportes com medidas padronizadas.', 'Um porta-retrato com foto de pessoas queridas e objetos decorativos que trazem memórias confortáveis.', 'Um suporte articulado para o monitor, organizadores de cabos sob a mesa e réguas de tomadas com proteção de surto.', 'src/img/imagem-1789050293039.jpg', '0000-00-00 00:00:00');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (73, 'Você foi convidado para planejar uma horta comunitária na sua rua ou condomínio. O que você assume?', 'A escolha de espécies companheiras, adubação de solo com compostagem e controle ecológico de insetos.', 'O cálculo do volume de terra e adubo necessários por metro linear de canteiro e a divisão das cotas financeiras.', 'A mobilização dos vizinhos em mutirões aos sábados, transformando o plantio em um espaço de união do bairro.', 'O projeto de irrigação automatizada por mangueiras microperfuradas acionadas por timers digitais.', 'src/img/imagem-1789050361483.jpg', '0000-00-00 00:00:00');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (74, 'Em um debate sobre sustentabilidade urbana, qual proposta você defenderia com mais convicção?', 'Criação de corredores ecológicos, plantio de árvores frutíferas nativas e despoluição de rios e córregos.', 'Incentivos fiscais calculados para empresas com baixa emissão de carbono e auditorias rigorosas de consumo de energia.', 'Programas de educação socioambiental em escolas públicas e apoio irrestrito a cooperativas de catadores de recicláveis.', 'Implantação de redes elétricas inteligentes (smart grids) e monitoramento por sensores da qualidade do ar em tempo real.', 'src/img/imagem-1789050438449.jpg', '0000-00-00 00:00:00');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (75, 'Ao adquirir um calçado esportivo para caminhadas ou treinos, qual aspecto você analisa com rigor?', 'O amortecimento de impacto na coluna, o suporte para a pisada e a respirabilidade do tecido para a pele do pé.', 'A durabilidade estimada da sola em quilômetros rodados em comparação ao valor financeiro cobrado pelo par.', 'A versatilidade do modelo para o dia a dia e se a fabricante possui políticas éticas comprovadas contra trabalho escravo.', 'Os materiais compósitos do solado com tecnologia de retorno de energia e palmilhas moldadas digitalmente.', 'src/img/imagem-1789050527339.jpg', '0000-00-00 00:00:00');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (76, 'Ao pensar na segurança da sua residência, qual medida você considera prioritária?', 'Manter o quintal limpo de entulhos para evitar animais peçonhentos e garantir que não haja vazamento de gás.', 'Orçar sistemas com três prestadores diferentes, calculando a relação entre custo de instalação e redução de sinistro.', 'Fortalecer o laço de confiança e vigilância mútua com os vizinhos mais próximos através de conversas constantes.', 'Instalar câmeras de vigilância IP com detecção de movimento e fechaduras biométricas integradas à rede Wi-Fi.', 'src/img/imagem-1789050851677.jpg', '0000-00-00 00:00:00');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (77, 'Se você precisasse criar um canal de vídeos na internet, qual seria a linha editorial?', 'Dicas práticas de saúde biológica, fitoterapia, culinária natural e cuidados com animais de estimação.', 'Análises financeiras, matemática do dia a dia, estatísticas esportivas e testes de rendimento de produtos.', 'Entrevistas sobre trajetórias de vida, causas sociais, resenhas de livros e reflexões sobre empatia.', 'Tutoriais de programação, montagem de computadores, inteligência artificial e novidades do ecossistema tech.', 'src/img/imagem-1789050642738.jpg', '0000-00-00 00:00:00');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (78, 'Em um parque florestal aberto, qual atividade mais atrai sua vontade?', 'Caminhar em silêncio observando a textura do solo, a copa das árvores centenárias e os animais em seu habitat.', 'Percorrer a trilha monitorando a velocidade média no cronômetro e a distância exata medida em metros.', 'Fazer um piquenique coletivo no gramado, contando histórias e aproveitando a convivência com as pessoas queridas.', 'Gravar imagens aéreas do parque com um drone portátil e mapear os trajetos em aplicativos de trilhas colaborativas.', 'src/img/imagem-1789050781722.jpg', '0000-00-00 00:00:00');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (79, 'Ao receber a conta mensal de água ou energia elétrica, o que você faz primeiro?', 'Conscientizo os moradores sobre a importância biológica de preservar a água para os ecossistemas do planeta.', 'Comparo o gráfico de barras de consumo dos últimos 12 meses, calculando a média diária e as variações de tarifa.', 'Converso gentilmente com todos na casa para entender se alguém teve uma necessidade pontual no período.', 'Acesso a agência virtual da concessionária no navegador ou app para baixar o arquivo detalhado e checar faturas via Pix.', 'src/img/imagem-1789051078110.jpg', '0000-00-00 00:00:00');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (80, 'Se você fosse reformar a cozinha de casa, o que seria o ponto central da obra?', 'Espaço adequado para higienização correta de hortaliças, ventilação natural para vapores e bancadas ergonômicas.', 'Orçamento rígido com cronograma de compras de materiais em atacado para evitar qualquer sobrecusto na mão de obra.', 'Um espaço amplo com mesa central convidativa, projetado para reunir a família enquanto a comida é preparada.', 'Eletrodomésticos embutidos conectados, tomadas inteligentes com USB e bancadas com cooktop de indução moderno.', 'src/img/imagem-1789051174528.jpg', '0000-00-00 00:00:00');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (81, 'Você foi encarregado de cuidar da logística de uma feira cultural do bairro. O que você prefere assumir?', 'A coordenação dos postos de atendimento de primeiros socorros e a distribuição de água potável ao público.', 'A contabilidade do evento: bilheteria, emissão de recibos, controle do fluxo de caixa e balanço final de contas.', 'A recepção dos artistas locais, a condução das rodas de conversa e a mediação com os visitantes da comunidade.', 'A operação dos sistemas de sonorização, transmissão ao vivo pela internet e a infraestrutura de redes locais.', 'src/img/imagem-1789051248324.jpg', '0000-00-00 00:00:00');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (82, 'Ao organizar suas roupas no guarda-roupa, como você decide a disposição?', 'Priorizo arejamento entre os tecidos naturais para evitar a formação de mofo e alergias respiratórias.', 'Agrupo as peças por categoria e frequência de uso, calculando a otimização de espaço por prateleira e gaveta.', 'Deixo à vista as roupas que guardam recordações afetivas de ocasiões marcantes e encontros felizes.', 'Utilizo organizadores modulares com etiquetas impressas e cabides padronizados de encaixe ergonômico moderno.', 'src/img/imagem-1789051302171.jpg', '0000-00-00 00:00:00');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (83, 'Ao planejar a decoração de uma festa de fim de ano, em que aspecto você mais foca?', 'No uso de folhagens naturais frescas, flores de época e materiais compostáveis para os arranjos.', 'Na compra antecipada em atacado, comparando preços para manter o custo total rigorosamente no orçamento planejado.', 'Na criação de um ambiente com murais de desejos, memórias dos momentos compartilhados no ano e luz suave.', 'No controle de fitas de iluminação LED RGB sincronizadas com música por aplicativo e projeções virtuais.', 'src/img/imagem-1789051340628.jpg', '0000-00-00 00:00:00');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (84, 'Se você precisasse escrever um artigo de opinião para um jornal local, qual tema escolheria?', 'A importância da preservação das praças arborizadas para a saúde pulmonar e a biodiversidade dos pássaros urbanos.', 'Uma análise do orçamento municipal, demonstrando matematicamente como cortar desperdícios em obras públicas.', 'A defesa da valorização dos centros comunitários e a necessidade de acolhimento humanizado na assistência social.', 'A modernização tecnológica das repartições públicas e a digitalização de serviços para acabar com as filas de papel.', 'src/img/imagem-1789051397485.jpg', '0000-00-00 00:00:00');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (85, 'Ao escolher um aplicativo novo para instalar no seu celular, qual critério te convence a mantê-lo?', 'Se ele me ajuda a regular a ingestão de água, monitorar a postura corporal ou melhorar a qualidade do sono.', 'Se ele não consome memória em excesso e me oferece ferramentas precisas de controle de despesas e produtividade.', 'Se ele facilita a comunicação genuína com familiares e amigos sem interfaces invasivas ou comerciais.', 'Se ele tem código bem estruturado, interface intuitiva, atualizações constantes e bons recursos de automação.', 'src/img/imagem-1789051462153.jpg', '0000-00-00 00:00:00');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (86, 'Você precisa adquirir uma mesa para estudar ou trabalhar. Em que detalhe você mais repara?', 'Na altura exata para que os antebraços fiquem em 90 graus, evitando tensões musculares na cervical e trapézio.', 'Na espessura da madeira compensada, na capacidade de peso suportado em quilos e no custo por centímetro de superfície.', 'Na beleza da madeira rústica, no aconchego visual que ela traz ao cômodo e na harmonia com o ambiente familiar.', 'Na existência de canaletas embutidas para passagem de cabos, suporte para réguas elétricas e portas USB na estrutura.', 'src/img/imagem-1789051518825.jpg', '0000-00-00 00:00:00');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (87, 'Ao visitar uma biblioteca histórica, qual detalhe mais chama sua atenção?', 'As técnicas usadas para evitar que traças, fungos e umidade destruam as fibras orgânicas do papel antigo.', 'O sistema exato de classificação decimal e a catalogação estatística de volumes por século e tema.', 'O silêncio compartilhado entre os leitores e o sentimento de reverência à sabedoria transmitida entre gerações.', 'As estações de escaneamento de microfilmes, os leitores ópticos e a digitalização de acervos raros em servidores.', 'src/img/imagem-1789051622960.jpg', '0000-00-00 00:00:00');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (88, 'Se você fosse convidado a ministrar uma oficina para jovens, qual tema você proporia?', 'Noções de primeiros socorros, identificação de plantas alimentícias não convencionais (PANCs) e saúde do corpo.', 'Educação financeira básica, matemática dos juros compostos e como montar um orçamento sem dívidas.', 'Comunicação não-violenta, técnicas de escuta empática, teatro comunitário e contação de histórias.', 'Introdução à lógica de programação, circuitos simples com sensores e montagem de projetos com placas microcontroladas.', 'src/img/imagem-1789051738131.jpg', '0000-00-00 00:00:00');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (89, 'Diante de um dia de sol intenso na praia ou no parque, qual é a sua preocupação prioritária?', 'A aplicação e reaplicação rigorosa de protetor solar, hidratação constante e proteção da visão com óculos escuros.', 'Controlar o tempo exato de exposição ao sol no relógio e limitar os gastos com quiosques para não estourar o orçamento.', 'Garantir que todos do grupo estejam confortáveis, dividindo guarda-sóis e conversando alegremente à beira da água.', 'Manter os aparelhos eletrônicos protegidos do superaquecimento e da areia, além de monitorar o índice UV pelo celular.', 'src/img/imagem-1789051785105.jpg', '0000-00-00 00:00:00');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (90, 'Ao organizar um arquivo de fotos pessoais de uma viagem, como você prefere fazer?', 'Selecionando as imagens que retratam paisagens naturais exuberantes, mares, animais e a vitalidade dos lugares.', 'Agrupando as fotos rigorosamente por data e hora de registro, calculando o tamanho total em megabytes da pasta.', 'Criando uma montagem com legendas afetivas sobre as amizades construídas e os momentos mais emocionantes vividos.', 'Subindo tudo para um serviço na nuvem com reconhecimento facial automático, geolocalização e backup redundante.', 'src/img/imagem-1789051870095.jpg', '0000-00-00 00:00:00');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (91, 'Se você participasse de um projeto de arquitetura para uma nova escola, onde concentraria seus palpites?', 'Na ventilação cruzada dos ambientes, na iluminação solar indireta e na implantação de jardins sensoriais.', 'Na planta baixa otimizada para reduzir custos de construção por metro quadrado e na durabilidade dos pisos.', 'Na concepção de pátios acolhedores que incentivem a convivência, a integração de alunos e a expressão artística.', 'Na infraestrutura de rede cabeada em todas as salas, laboratórios de computação modernos e projetores integrados.', 'src/img/imagem-1789051920151.jpg', '0000-00-00 00:00:00');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (92, 'Ao participar de uma gincana de desafios variados, qual tipo de prova você prefere encarar?', 'Uma prova de resistência física ou corrida de orientação pela natureza identificando pistas em trilhas.', 'Um enigma matemático complexo ou problema de probabilidade com tempo limitado para resposta.', 'Uma prova de encenação de teatro improvisado ou uma dinâmica que exija diálogo e cooperação com o público.', 'Um desafio de decifrar códigos lógicos em computador ou montar um circuito elétrico funcional contra o relógio.', 'src/img/imagem-1789051970281.jpg', '0000-00-00 00:00:00');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (93, 'Ao escolher um restaurante por aplicativo para pedir comida em casa, o que é determinante?', 'A garantia de que os alimentos são preparados com itens frescos, nutritivos e com pouca gordura saturada.', 'A relação entre o valor da taxa de entrega, cupons de desconto aplicados e o preço total por porção servida.', 'O carinho percebido nas embalagens de pequenos negócios de família que enviam bilhetes personalizados e gentis.', 'O tempo estimado de entrega em tempo real rastreado por satélite e o histórico de avaliações algorítmicas do local.', 'src/img/imagem-1789052068042.jpg', '0000-00-00 00:00:00');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (94, 'Diante de um impasse ou desentendimento em um grupo do qual faz parte, como você se posiciona?', 'Sugiro uma pausa para respirar fundo, caminhar um pouco e baixar a adrenalina antes de continuar qualquer conversa.', 'Apresento os dados objetivos e regras combinadas de forma imparcial, demonstrando friamente a lógica de cada ponto.', 'Escuto com atenção o sentimento de cada pessoa envolvida, buscando restabelecer a confiança e a harmonia mútua.', 'Proponho abrir uma votação anônima por formulário digital rápido para que a decisão seja registrada de forma clara e ágil.', 'src/img/imagem-1789052113158.jpg', '0000-00-00 00:00:00');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (95, 'Ao escolher um novo par de óculos de sol ou de grau, o que é fundamental para você?', 'A proteção total contra raios UVA/UVB e o conforto nasal das plaquetas para não machucar a pele com o uso contínuo.', 'A comparação de preços entre diferentes óticas e a análise da durabilidade dos materiais da armação pelo preço cobrado.', 'Como a armação harmoniza com o formato do rosto e transmite a minha personalidade nas relações com as pessoas.', 'Lentes com tratamentos antirreflexo de última geração e armações produzidas por ligas metálicas com memória de forma.', 'src/img/imagem-1789052157921.jpg', '0000-00-00 00:00:00');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (96, 'Se você pudesse passar um mês estagiando em uma instituição de prestígio, qual escolheria?', 'Um instituto botânico ou hospital de pesquisas focado em terapias celulares e conservação biológica.', 'Um departamento de estatística aplicada, auditoria financeira ou centro de pesquisas em engenharia quantitativa.', 'Uma fundação internacional de defesa dos direitos humanos, história oral e patrimônio cultural comunitário.', 'Um laboratório avançado de desenvolvimento de inteligência artificial, computação quântica e robótica autônoma.', 'src/img/imagem-1789052195988.jpg', '0000-00-00 00:00:00');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (97, 'Ao arrumar sua despensa de alimentos, qual critério você segue?', 'Coloco na frente os itens com prazo de validade mais próximo para evitar deterioração biológica e consumo fresco.', 'Agrupo latas e caixas por volume e tamanho, calculando a capacidade máxima de peso suportada por prateleira.', 'Separo os ingredientes que usamos para fazer as receitas clássicas de família nos almoços de domingo.', 'Uso potes herméticos padronizados com etiquetas codificadas e registro as quantidades em uma lista no celular.', 'src/img/imagem-1789052268006.jpg', '0000-00-00 00:00:00');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (98, 'Diante de uma mudança repentina no trajeto usual do seu transporte, como você reage?', 'Aproveito a caminhada extra para exercitar as pernas e respirar ao ar livre, apreciando a mudança de ritmo corporal.', 'Calculo rapidamente a nova estimativa de atraso em minutos e a diferença eventual de tarifa para recalcular os custos.', 'Converso com outros passageiros para ver se alguém também está desorientado e juntos buscamos o caminho correto.', 'Abro imediatamente o aplicativo de mapas com monitoramento em tempo real para recalcular a rota alternativa ideal.', 'src/img/imagem-1789052301188.jpg', '0000-00-00 00:00:00');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (99, 'Ao planejar a iluminação externa de um quintal ou varanda, o que orienta seu plano?', 'Escolho lâmpadas com temperatura de cor que não afaste pássaros noturnos nem desoriente insetos polinizadores.', 'Dimensiono a quantidade exata de watts necessária para clarear os metros quadrados sem gerar desperdício elétrico.', 'Posiciono focos de luz suave e convidativa em áreas de estar, criando um espaço acolhedor para receber visitas.', 'Instalo refletores solares autônomos com sensores de presença e acionamento programado via automação sem fio.', 'src/img/imagem-1789052349727.jpg', '0000-00-00 00:00:00');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (100, 'Ao participar de uma feira de ciências ou tecnologia, qual estande prenderia mais a sua atenção?', 'Experimentos com microrganismos decompositores, purificadores ecológicos de água e hidroponia caseira.', 'Modelos físicos com demonstrações de cinemática, cálculo de pontes de treliça e simulações probabilísticas.', 'Painéis interativos sobre a história das profissões, desigualdade no acesso à educação e cultura popular.', 'Demonstrações de visão computacional, braços robóticos com controle remoto e redes neurais treinadas ao vivo.', 'src/img/imagem-1789052398930.jpg', '0000-00-00 00:00:00');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (101, 'Ao comprar um ventilador ou climatizador para o verão, qual detalhe é prioritário?', 'A presença de filtros de ar eficientes para reter poeira e o silêncio do motor para não prejudicar o sono profundo.', 'A etiqueta de eficiência energética Procel nível A e o cálculo do consumo em reais por hora de funcionamento diário.', 'O conforto térmico compartilhado no cômodo onde a família se reúne para assistir TV e conversar.', 'O controle de velocidade por controle remoto ou comando de voz via assistente virtual e temporizador digital.', 'src/img/imagem-1789052443180.jpg', '0000-00-00 00:00:00');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (102, 'Quando você reflete sobre o legado que gostaria de deixar com o seu trabalho, qual pensamento predomina?', 'Ter ajudado a curar doenças, restaurado o meio ambiente ou melhorado as condições biológicas de vida das pessoas.', 'Ter construído sistemas eficientes, gerido recursos com honestidade matemática e garantido sustentabilidade econômica.', 'Ter tocado corações, ensinado novas gerações, promovido a justiça social e deixado memórias de afeto e cidadania.', 'Ter criado tecnologias inovadoras, desenvolvido softwares transformadores e expandido as fronteiras digitais da humanidade.', 'src/img/imagem-1789052477395.jpg', '0000-00-00 00:00:00');
--
-- Índices para tabelas despejadas
--

--
-- Índices de tabela `cadastro`
--
ALTER TABLE `cadastro`
  ADD PRIMARY KEY (`id`);

--
-- Índices de tabela `questoes`
--
ALTER TABLE `questoes`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT para tabelas despejadas
--

--
-- AUTO_INCREMENT de tabela `cadastro`
--
ALTER TABLE `cadastro`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;

--
-- AUTO_INCREMENT de tabela `questoes`
--
ALTER TABLE `questoes`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=32;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;