-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Versão do servidor: 10.4.32-MariaDB
-- Versão do PHP: 8.0.30

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Banco de dados: `testevocacional`
--

-- --------------------------------------------------------

--
-- Estrutura para tabela `cadastro`
--

CREATE TABLE `cadastro` (
  `id` int(11) NOT NULL,
  `nome` varchar(150) NOT NULL,
  `email` varchar(150) NOT NULL,
  `whatsapp` varchar(30) NOT NULL,
  `pontos_biologicas` int(11) DEFAULT 0,
  `pontos_exatas` int(11) DEFAULT 0,
  `pontos_humanas` int(11) DEFAULT 0,
  `pontos_tecnologicas` int(11) DEFAULT 0,
  `perfil_predominante` varchar(50) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------

--
-- Estrutura para tabela `questoes`
--

CREATE TABLE `questoes` (
  `id` int(11) NOT NULL,
  `questao` text NOT NULL,
  `opcaoA` varchar(255) NOT NULL,
  `opcaoB` varchar(255) NOT NULL,
  `opcaoC` varchar(255) NOT NULL,
  `opcaoD` varchar(255) NOT NULL,
  `imagem` varchar(255) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Despejando dados para a tabela `questoes`
--

INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (1, 'Na hora de organizar o porta-malas do carro para uma longa viagem com a família ou amigos, como você costuma agir ou o que prioriza?', 'Priorizo acomodar em local de fácil acesso a caixa térmica com alimentos frescos, bastante água, o kit de primeiros socorros/remédios e o espaço seguro para o transporte do pet.', 'Analiso a geometria do espaço: distribuo as malas mais pesadas na base para equilibrar o centro de gravidade do veículo e encaixo cada volume calculando o melhor aproveitamento do espaço útil.', 'Garanto que a bagagem de cada pessoa tenha seu lugar respeitado e deixo à mão itens que tragam conforto e bem-estar para o trajeto, como travesseiros, jogos para o grupo e lembranças da viagem.', 'Separo um compartimento para todos os adaptadores, cabos, powerbanks e suportes, checando se os dispositivos móveis e ferramentas digitais de rota estão carregados e organizados.', 'src\\img\\imagem-1788750275205.jpg', 'Mon Sep 07 2026 00:04:35 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (2, 'Você ficou responsável por organizar e comprar os comes e bebes para um encontro com amigos ou família no final de semana. Como você planeja e executa essa tarefa?', 'Foco na qualidade e procedência dos itens: seleciono opções frescas, verifico ingredientes para atender quem tem restrições alimentares (como alergias ou intolerâncias) e garanto opções saudáveis e hidratação adequada.', 'Calculo as quantidades exatas por pessoa com base na duração do evento, comparo o preço por quilo/litro entre marcas e controlo os gastos rigorosamente para que a divisão da conta seja precisa e sem desperdício.', 'Converso com o grupo para entender as preferências de cada um, priorizando pratos que tragam boas lembranças, criem uma atmosfera afetiva e façam todos se sentirem confortáveis e acolhidos.', 'Uso aplicativos para calcular o consumo, faço cotação de preços online com entrega rápida e utilizo planilhas ou apps de divisão de contas automática com Pix para facilitar a organização.', 'src\\img\\imagem-1788751090913.jpg', 'Mon Sep 07 2026 00:18:10 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (3, 'Você decidiu iniciar uma nova atividade física para manter uma rotina mais ativa no dia a dia. Ao escolher a modalidade e acompanhar sua evolução, qual é a sua principal abordagem?', 'Avalio como o exercício afeta meus músculos, respiração e postura, buscando entender a recuperação biológica do corpo, a nutrição adequada e os benefícios para a minha saúde a longo prazo.', 'Defino metas com base em números exatos: calculo calorias gastas, meço a evolução de cargas ou tempo por quilômetro e analiso tabelas de rendimento para otimizar meu progresso.', 'Priorizo modalidades que permitam interação social, trabalho em equipe ou que tragam equilíbrio mental, usando o momento da atividade para aliviar as pressões do dia e me reconectar com as pessoas.', 'Uso relógios inteligentes, sensores e aplicativos com dashboards que registram dados em tempo real, testando novos equipamentos e comparando relatórios automáticos de desempenho.', 'src/img/imagem-1788755178366.jpg', 'Mon Sep 07 2026 01:26:18 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (4, 'Você decidiu renovar e reorganizar um cômodo da sua casa (como o quarto ou a sala de estudos/trabalho). Qual aspecto você prioriza no planejamento dessa mudança?', 'Priorizo a circulação de ar natural, a entrada de luz solar, a presença de plantas e a ergonomia dos móveis, garantindo um ambiente biologicamente saudável que favoreça a respiração e a postura.', 'Tiro as medidas exatas do espaço, calculo a área de piso e parede para estimar o consumo exato de materiais sem sobras e monto uma planilha de custos para manter o projeto dentro do orçamento planejado.', 'Foco na sensação de acolhimento e identidade pessoal: escolho cores que transmitam calma, crio um espaço agradável para receber pessoas ou estudar em família e reservo um lugar para fotos e lembranças.', 'Planejo a distribuição de tomadas, cabos de rede e repetidores de sinal, integrando iluminação inteligente controlada por aplicativo e assistentes virtuais para automatizar as rotinas do cômodo.', 'src/img/imagem-1788755246082.jpg', 'Mon Sep 07 2026 01:27:26 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (5, 'Você precisa escolher um novo eletrodoméstico para a casa (como uma geladeira ou ar-condicionado). Diante de vários modelos disponíveis, em qual critério você baseia sua decisão de compra?', 'Analiso os benefícios diretos para a saúde e o ambiente: filtros antibacterianos, níveis de conservação biológica de alimentos, purificação do ar e o baixo nível de ruído para preservar a qualidade do sono.', 'Calculo a relação custo-benefício matemática: comparo o consumo de energia em kWh na conta de luz, o tempo de amortização do valor investido e as medidas milimétricas em relação ao espaço disponível.', 'Leio relatos e avaliações de outros usuários sobre a facilidade de uso no cotidiano e priorizo um design acolhedor que combine com o convívio e a harmonia das pessoas que moram na casa.', 'Priorizo modelos com recursos inteligentes: controle via aplicativo, integração com sistemas de automação residencial, sensores modernos e alertas automáticos de funcionamento e manutenção.', 'src/img/imagem-1788755481918.jpg', 'Mon Sep 07 2026 01:31:21 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (6, 'Ao planejar uma viagem ou passeio de fim de semana com amigos ou família, qual aspecto ou detalhe você costuma priorizar para garantir que tudo dê certo', 'Priorizo roteiros ao ar livre e contato com a natureza: verifico a preservação das trilhas e praias, a qualidade da água, o clima local e garanto pausas para hidratação e recuperação física do grupo.', 'Monto um cronograma financeiro exato: calculo gastos com combustível por quilômetro rodado, pedágios, estimativa de alimentação diária e mantenho uma planilha para não estourar o orçamento previsto.', 'Pesquiso a história da região, tradições culturais e costumes locais, buscando passeios que proporcionem boas conversas, pratos típicos e memórias afetivas para fortalecer os laços entre as pessoas.', 'Organizo tudo por meios digitais: comparo rotas e trânsito em tempo real por mapas virtuais, centralizo reservas em aplicativos e garanto internet móvel estável e carregadores portáteis para a rota.', 'src/img/imagem-1788782919657.jpg', 'Mon Sep 07 2026 09:08:39 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (7, 'Você decidiu cultivar algumas plantas, flores ou uma pequena horta em casa (no quintal ou na varanda). Qual é a sua principal atenção no cuidado desse cultivo?', 'Observo atentamente a fisiologia das plantas: a coloração das folhas, a exposição correta à luz solar, a drenagem do solo e o uso de adubação orgânica para prevenir pragas de forma natural.', 'Calculo com precisão as proporções de terra, areia e nutrientes para o substrato, meço o volume ideal de cada vaso e controlo o orçamento gasto com mudas e insumos.', 'Encaro o cultivo como um momento terapêutico para desacelerar da rotina, escolhendo espécies que tragam memórias afetivas e deixem o ambiente mais acolhedor para a família e amigos.', 'Instalo um sistema de irrigação por gotejamento com temporizador ou sensores de umidade no solo, buscando automatizar os cuidados e monitorar o ambiente por aplicativos.', 'src/img/imagem-1788783197226.jpg', 'Mon Sep 07 2026 09:13:17 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (8, 'Você tem uma semana intensa pela frente, com vários prazos, tarefas e compromissos para entregar. Como você estrutura sua rotina para dar conta de tudo sem se sobrecarregar?', 'Respeito os limites do meu organismo: planejo horários fixos para dormir, garanto refeições balanceadas, mantenho uma garrafa d\'água sempre por perto e faço pausas regulares para alongar a coluna e descansar a visão.', 'Distribuo as horas do dia em blocos exatos de tempo: calculo a estimativa de minutos para cada tarefa, ordeno por nível de complexidade e acompanho graficamente a taxa de entrega para não estourar nenhum prazo.', 'Converso com as pessoas envolvidas para negociar expectativas e prazos com empatia, reservando momentos para descontrair, desabafar com amigos e manter o ambiente de trabalho ou estudo colaborativo e leve.', 'Centralizo tudo em aplicativos de tarefas sincronizados em nuvem, programo lembretes automáticos no celular e utilizo ferramentas digitais ou inteligência artificial para otimizar etapas repetitivas da rotina', 'src/img/imagem-1788783461980.jpg', 'Mon Sep 07 2026 09:17:41 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (9, 'Ao organizar o descarte de materiais, embalagens e restos do cotidiano na sua casa, qual aspecto você mais prioriza para adotar uma postura sustentável?', 'Separo os resíduos orgânicos para compostagem e adubação natural, avaliando o tempo de biodegradação dos itens para evitar a contaminação do solo e dos lençóis freáticos.', 'Meço a redução de volume do lixo gerado, calculo a economia no reaproveitamento de recipientes e estimo o percentual de materiais recicláveis desviados dos aterros sanitários.', 'Higienizo e embalo os recicláveis com segurança para valorizar o trabalho dos catadores e cooperativas locais, incentivando familiares e vizinhos a adotarem o mesmo cuidado social.', 'Uso aplicativos para localizar ecopontos especializados de eletrônicos e baterias, consulto guias interativos de reciclagem e acompanho soluções de logística reversa inteligente.', 'src/img/imagem-1788785331927.jpg', 'Mon Sep 07 2026 09:48:51 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (10, 'Ao preparar um café da manhã ou um lanche reforçado antes de começar o dia, em qual detalhe você mais concentra sua atenção?', 'No equilíbrio nutricional dos alimentos: combino proteínas, fibras e frutas frescas para garantir energia duradoura, facilitar a digestão e manter o organismo funcionando bem ao longo da manhã.', 'Nas medidas e proporções precisas: peso ou meço os ingredientes com exatidão, controlo rigorosamente o tempo de fogo ou forno e calculo a porção exata para evitar desperdício de insumos.', 'No valor afetivo e acolhedor da refeição: escolho receitas que tragam conforto e boas lembranças, capricho na apresentação da mesa e aproveito o momento para conversar com quem está por perto.', 'Na praticidade dos aparelhos inteligentes: uso cafeteiras programáveis, timers digitais ou air fryer com receitas salvas para otimizar o tempo e garantir o ponto ideal sem esforço manual.', 'src/img/imagem-1788785527140.jpg', 'Mon Sep 07 2026 09:52:07 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (11, 'Ao definir como você vai se deslocar pela cidade para um compromisso diário (escola, trabalho ou curso), qual critério mais influencia sua escolha de transporte e rota?', 'Priorizo opções ativas ou ao ar livre, como caminhar ou pedalar parte do caminho, avaliando o benefício físico do exercício, a oxigenação do corpo e a menor exposição a ambientes abafados.', 'Calculo com precisão a relação custo-benefício: meço o tempo exato de percurso, comparo o valor de passagens ou consumo de combustível por quilômetro e escolho a alternativa mais econômica e pontual', 'Prefiro combinar caronas com conhecidos ou usar transporte coletivo para observar o movimento da cidade, valorizando a troca com outras pessoas e a gentileza no trânsito.', 'Consulto aplicativos de navegação em tempo real para fugir de congestionamentos, uso bilhete ou pagamento digital por aproximação e acompanho a previsão exata de chegada por satélite.', 'src/img/imagem-1788785688409.jpg', 'Mon Sep 07 2026 09:54:48 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (12, 'Você foi convidado para participar da organização de um evento voluntário ou comunitário no seu bairro. Em qual frente você prefere atuar?', 'Na triagem de arrecadação de alimentos perecíveis e medicamentos, checando condições de validade, higiene e orientações básicas de saúde preventiva.', 'No controle financeiro e orçamentário: cálculo de custos de infraestrutura, prestação de contas exata e análise quantitativa do público atendido.', 'Na recepção e atendimento direto ao público, escutando as histórias da comunidade, mediando conversas e promovendo a inclusão de todos.', 'No desenvolvimento e gestão das inscrições online, transmissão ao vivo, suporte técnico de som/rede e divulgação automatizada nas redes.', 'src/img/imagem-1788828893937.jpg', 'Mon Sep 07 2026 21:54:53 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (13, 'Ao planejar a compra de roupas ou calçados para o seu uso diário, qual critério tem mais peso na sua decisão?', 'Priorizo tecidos de fibras naturais e respiráveis, calçados com suporte anatômico/ergonômico para a coluna e itens hipoalergênicos.', 'Avalio o custo por uso (preço dividido pela durabilidade esperada), comparo porcentagens de desconto e mantenho o gasto rigorosamente dentro do orçamento.', 'Busco saber a história da marca, se há respeito aos direitos trabalhistas na confecção e priorizo peças que expressem minha identidade e cultura.', 'Prefiro peças com tecidos tecnológicos (secagem ultra-rápida, repelentes de água ou odor) e pesquiso avaliações em plataformas e comparadores digitais.', 'src/img/imagem-1788829034497.jpg', 'Mon Sep 07 2026 21:57:14 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (14, 'Você decide adotar um animal de estimação ou ajudar a cuidar do pet de um amigo. Qual é o seu foco principal nessa responsabilidade?', 'Preocupo-me com o calendário de vacinas, a qualidade biológica da ração, a saúde digestiva, o peso do animal e as visitas preventivas ao veterinário.', 'Calculo os gastos mensais com alimentação e remédios, meço as gramas exatas de ração diária por peso corporal e cronometro os horários fixos de passeio', 'Foco na adaptação emocional do animal, criando um vínculo de afeto, acolhimento e garantindo que ele se sinta seguro e parte integrante da família.', 'Utilizo coleiras inteligentes com GPS, bebedouros/comedouros automáticos programáveis e aplicativos de celular para monitorar o histórico e rotina do pet.', 'src/img/imagem-1788829247887.jpg', 'Mon Sep 07 2026 22:00:47 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (15, 'Você decide reformular seu padrão de sono e descanso noturno para render melhor durante o dia. Como você aborda isso?', 'Estudo os ciclos biológicos do sono, evito cafeína à noite, regulo a alimentação noturna e presto atenção aos níveis de relaxamento muscular do corpo.', 'Calculo o número exato de horas e ciclos de sono de 90 minutos, tabulando a média semanal para identificar variações matemáticas de energia.', 'Pratico momentos de descompressão mental com leituras reflexivas, diários ou conversas tra', 'Utilizo smartbands, relógios ou anéis inteligentes com sensores de batimentos e oxigenação para analisar gráficos automáticos de sono profundo via app.', 'src/img/imagem-1788829449670.jpg', 'Mon Sep 07 2026 22:04:09 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (16, 'Durante uma caminhada pelo seu bairro ou parque, o que mais desperta sua curiosidade e atenção?', 'A variedade de árvores, pássaros e insetos, observando como a vegetação urbana reage ao clima e à poluição da cidade.', 'A geometria dos edifícios, a velocidade média do tráfego, os cálculos de fluxo e a proporção de espaço entre calçadas e pistas.', 'O comportamento das pessoas, as interações sociais, as expressões culturais dos transeuntes e a história por trás dos pontos históricos do bairro.', 'A fiação subterrânea ou aérea, a presença de câmeras de reconhecimento, totens de recarga, painéis solares e antenas 5G espalhadas pelo local.', 'src/img/imagem-1788829771026.jpg', 'Mon Sep 07 2026 22:09:31 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (17, 'Você vai preparar uma apresentação ou trabalho para apresentar publicamente. Qual etapa você prioriza com mais entusiasmo?', 'Investigar evidências baseadas na saúde, meio ambiente ou impacto na vida cotidiana das pessoas, trazendo exemplos práticos da natureza humana.', 'Estruturar a apresentação com dados estatísticos sólidos, gráficos precisos, métricas numéricas e uma linha de raciocínio estritamente lógica.', 'Construir uma narrativa envolvente (storytelling), adaptando a linguagem para engajar emocionalmente o público e gerar empatia com a mensagem.', 'Configurar slides interativos, recursos audiovisuais modernos, ferramentas digitais de votação em tempo real e automações visuais de ponta.', 'src/img/imagem-1788830000378.jpg', 'Mon Sep 07 2026 22:13:20 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (18, 'Se você pudesse escolher um tema de documentário ou série para maratonar no fim de semana, qual escolheria?', 'A vida selvagem, os mistérios do cérebro humano, medicina preventiva ou a complexidade dos ecossistemas marinhos.', 'Enigmas da física, matemática aplicada às finanças, engenharia de megaestruturas ou astronomia quantitativa do universo.', 'Documentários sobre acontecimentos históricos, movimentos sociais, comportamento humano, biografias inspiradoras e diversidade cultural.', 'A evolução da inteligência artificial, cibernética, viagens espaciais tripuladas, robótica e inovações que moldarão o futuro digital.', 'src/img/imagem-1788830226551.jpg', 'Mon Sep 07 2026 22:17:06 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (19, 'Em uma situação de crise ou emergência que exige tomada de decisão rápida, qual é a sua postura natural?', 'Verifico imediatamente a integridade física e respiratória das pessoas, aplicando primeiros socorros ou buscando condições seguras de sobrevivência.', 'Avalio os riscos de forma fria e lógica, calculando as probabilidades de cada alternativa para escolher o caminho de menor perda estatística.', 'Busco manter o grupo calmo, prestando apoio psicológico, mediando conflitos de pânico e garantindo que ninguém se sinta desamparado.', 'Acesso canais digitais de emergência, consulto dados em tempo real via celular e utilizo ferramentas eletrônicas para solucionar o bloqueio rapidamente.  Pergunta 20', 'src/img/imagem-1788830382424.jpg', 'Mon Sep 07 2026 22:19:42 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (20, 'Ao escolher um destino de férias, o que mais atrai a sua vontade de viajar?', 'Destinos com ecoturismo preservado, parques nacionais, praias com recifes de corais e trilhas imersas em florestas nativas.', 'Cidades com roteiros detalhadamente orçados, onde posso calcular o melhor retorno financeiro para cada dia investido na viagem.', 'Lugares ricos em patrimônio histórico, museus', 'Metrópoles ultramodernas repletas de arranha-céus, cidades inteligentes, museus de ciência interativos e mobilidade 100% digital.', 'src/img/imagem-1788830594670.jpg', 'Mon Sep 07 2026 22:23:14 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (21, 'Você precisa escolher um hobby manual para praticar nas horas livres. Qual destas opções mais combina com você?', 'Jardinagem com plantas medicinais, cuidados com terrários ou apicultura urbana.', 'Jogos de xadrez avançado, aeromodelismo em escala milimétrica ou quebra-cabeças complexos de lógica.', 'Escrita criativa, pintura de retratos, clube de leitura ou teatro amador.', 'Montagem de peças de computadores, pilotagem de drones, eletrônica com placas Arduino ou impressão 3D.', 'src/img/imagem-1788830702461.jpg', 'Mon Sep 07 2026 22:25:02 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (22, 'Ao ler as notícias do dia em um portal de informações, qual manchete chama sua atenção primeiro?', 'Descobertas sobre novos tratamentos de saúde, conservação ambiental ou avanços no combate a pandemias.', 'Variação de taxas de juros, relatórios econômicos, projeções orçamentárias ou estatísticas de mercado.', 'Debates sobre direitos sociais, impactos da educação na sociedade, história das comunidades ou manifestações culturais.', 'Lançamentos de novos chips, avanços em softwares de automação, computação quântica e segurança da informação.', 'src/img/imagem-1788830918030.jpg', 'Mon Sep 07 2026 22:28:38 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (23, 'Diante de um problema com a água encanada ou infiltração em sua casa, qual aspecto você investiga primeiro?', 'Avalio se há risco de contaminação bacteriana, presença de mofo prejudicial à respiração ou acúmulo de larvas de insetos.', 'Meço a vazão pelo hidrômetro, calculo a pressão hidráulica e estimo o custo do desperdício de água no valor final da conta.', 'Converso com vizinhos ou com o condomínio para entender se o problema afeta a convivência do prédio e busco um acordo amigável.', 'Pesquiso na internet tutoriais detalhados de diagnóstico e utilizo sensores de vazamento ou ferramentas especializadas para achar a falha.', 'src/img/imagem-1788831071217.jpg', 'Mon Sep 07 2026 22:31:11 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (24, 'Se você fosse criar um projeto para melhorar a escola ou local de trabalho, qual seria a sua prioridade?', 'Melhorar a qualidade das refeições no refeitório, criar espaços verdes ao ar livre e programas de conscientização sobre saúde mental e física.', 'Otimizar a grade de horários, reestruturar a alocação do orçamento e criar métricas claras para medir o desempenho de todos.', 'Criar programas de mentoria, círculos de diálogo contra o preconceito e projetos culturais que fortaleçam os vínculos de amizade.', 'Modernizar a rede Wi-Fi, digitalizar processos manuais por meio de plataformas na nuvem e equipar salas com telas interativas.', 'src/img/imagem-1788831268036.jpg', 'Mon Sep 07 2026 22:34:28 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (25, 'Ao escolher um livro em uma livraria ou biblioteca, qual prateleira costuma te prender por mais tempo?', 'Seção de biologia geral, nutrição, neurociência, zoologia e conservação ambiental.', 'Seção de matemática pura, física teórica, estatística, economia quantitativa ou investimentos.', 'Seção de filosofia, sociologia, psicologia social, história mundial e ficção clássica.', 'Seção de ciência da computação, programação, inovação digital, inteligência artificial e engenharia de sistemas.', 'src/img/imagem-1788831439720.jpg', 'Mon Sep 07 2026 22:37:19 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (26, 'Quando você se depara com um produto com defeito que comprou recentemente, qual é o seu primeiro impulso?', 'Verifico se o material pode liberar substâncias tóxicas, se há riscos alérgicos ou perigo físico imediato a quem manuseia.', 'Calculo os prazos legais de garantia, a perda financeira e organizo todos os comprovantes e notas fiscais com precisão.', 'Tento um diálogo compreensivo e educado com o vendedor ou atendente, buscando entender o lado do prestador e negociar com empatia.', 'Abro o chamado via chat automático/bot, registro fotos do defeito no portal e busco nos fóruns da internet se é um defeito de fábrica conhecido.  Pergunta 27', 'src/img/imagem-1788831614187.jpg', 'Mon Sep 07 2026 22:40:14 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (27, 'Se você fosse chamado para organizar a biblioteca comunitária da sua região, como você classificaria as obras?', 'Dando destaque a seções práticas sobre anatomia, guias botânicos, primeiros socorros e guias de agricultura urbana e saúde.', 'Criando uma codificação numérica e decimal rigorosa, calculando índices de empréstimo e projetando rotatividade por cálculo estatístico.', 'Agrupando livros por movimentos literários e períodos históricos, criando espaços confortáveis de debate e incentivo à leitura.', 'Implementando etiquetas RFID/código de barras, catálogo 100% digital na nuvem e totens de autoatendimento para devolução.', 'src/img/imagem-1788831989927.jpg', 'Mon Sep 07 2026 22:46:29 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (28, 'Ao começar a aprender a cozinhar pratos mais elaborados, qual é o seu principal estilo na cozinha?', 'Observo como o cozimento altera as propriedades dos nutrientes, a conservação orgânica e o ponto biológico ideal de carnes e vegetais.', 'Sigo as receitas como uma fórmula matemática: balança digital para pesar cada grama, termômetro culinário e cronômetro ativado.', 'Encaro a comida como afeto e memória cultural: improviso temperos de família e cozinho pensando no prazer de reunir as pessoas.', 'Utilizo eletroportáteis modernos de precisão (sous-vide, fornos por indução ou receitas em aplicativos inteligentes com timer integrado).  Pergunta 29', 'src/img/imagem-1788832203440.jpg', 'Mon Sep 07 2026 22:50:03 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (29, 'Como você costuma gerenciar suas senhas e contas de acessos pessoais?', 'Uso autenticação por biometria (impressão digital ou leitura facial), valorizando a identidade orgânica única do meu corpo.', 'Crio combinações lógicas baseadas em fórmulas alfanuméricas estruturadas, trocando periodicamente com base em intervalos exatos de dias.', 'Escolho palavras que remetem a lembranças afetivas significativas ou nomes importantes da minha história para não esquecer.', 'Utilizo gerenciadores de senhas em nuvem com criptografia de ponta a ponta e chaves de segurança com verificação em duas etapas (2FA).', 'src/img/imagem-1788832350897.jpg', 'Mon Sep 07 2026 22:52:30 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (30, 'Se você participasse da fundação de uma nova cidade ou bairro planejado, em qual setor gostaria de opinar?', 'Na preservação dos mananciais hídricos, arborização de espécies nativas, saneamento biológico e equilíbrio da fauna local.', 'No traçado viário simétrico, dimensionamento de cargas elétricas, cálculo de vazão de águas pluviais e viabilidade orçamentária.', 'Na distribuição democrática de praças, centros culturais comunitários, escolas acessíveis e incentivo à convivência coletiva.', 'Na infraestrutura de cabeamento de alta velocidade, postes inteligentes, sensores urbanos IoT e sistemas de mobilidade autônoma.', 'src/img/imagem-1788832482295.jpg', 'Mon Sep 07 2026 22:54:42 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (31, 'Diante de uma notícia polêmica nas redes sociais sobre o futuro do trabalho, qual ângulo mais desperta sua reflexão?', 'O impacto do estresse e do excesso de telas na saúde física, ergonômica e no sistema imunológico dos trabalhadores.', 'A análise estatística de aumento de produtividade, custos corporativos e a margem de retorno sobre os postos de trabalho.', 'Os dilemas éticos da substituição do trabalho humano, a desigualdade social gerada e a perda de conexões interpessoais.', 'Quais ferramentas de software e algoritmos estão liderando essa transformação e como dominar a nova infraestrutura digital.', 'src/img/imagem-1788832604610.jpg', 'Mon Sep 07 2026 22:56:44 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (32, 'Você decidiu pintar as paredes do seu quarto ou de uma sala da sua casa. Qual aspecto você prioriza durante o planejamento e a execução do trabalho?', 'Escolho tintas ecológicas sem odor ou à base d\'água e com componentes antimofo, mantendo janelas bem abertas para garantir a qualidade do ar e a saúde respiratória durante o processo.', 'Calculo a área total das paredes em metros quadrados, desconto as aberturas de portas e janelas e estimo o rendimento exato em litros por demão para evitar desperdício e custos extras.', 'Pesquiso o significado e a psicologia das cores para selecionar tons que transmitam paz, harmonia e acolhimento para todos que compartilham o ambiente no dia a dia.', 'Utilizo pistolas elétricas de pintura pulverizada, testo simuladores virtuais de cores por realidade aumentada no celular e pesquiso tintas com tecnologia de isolamento térmico.', 'src/img/imagem-1788923600478.jpg', 'Wed Sep 09 2026 00:13:20 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (33, 'No seu tempo livre dedicado ao seu hobby predileto, qual é o principal elemento que te mantém motivado e focado nessa atividade?', 'A sensação de reequilíbrio corporal e alívio do estresse biológico, percebendo como a prática desacelera meus batimentos, descansa a mente e restaura minha disposição física.', 'A evolução lógica e matemática da prática: analisar pontuações, comparar tempos, dominar regras com precisão cirúrgica e traçar estratégias para otimizar meu rendimento.', 'A oportunidade de compartilhar o momento com amigos, participar de clubes/encontros comunitários ou produzir algo com significado afetivo e cultural para presentear pessoas queridas.', 'Explorar novos recursos digitais, configurar periféricos avançados, atualizar hardwares ou programar rotinas e mods para aperfeiçoar a experiência técnica do passatempo.', 'src/img/imagem-1788923970076.jpg', 'Wed Sep 09 2026 00:19:30 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (34, 'Você vai a um grande festival ou show de música ao vivo com apresentações de vários artistas. O que mais chama sua atenção e define sua preparação para o evento?', 'Planejo pausas para hidratação constante, escolho roupas e tênis com suporte anatômico e fico atento à alimentação adequada para aguentar horas em pé sem prejudicar o corpo.', 'Analiso o mapa do evento para calcular o tempo exato de deslocamento entre palcos, controlo os custos de transporte e consumo e cronometro os horários para ver todas as atrações sem atraso.', 'A energia do público cantando em uníssono, a mensagem das letras, a história dos movimentos musicais e a conexão emocional estabelecida entre os artistas e a multidão.', 'O espetáculo dos painéis de LED de alta definição, os efeitos visuais sincronizados por software, a engenharia da mesa de som digital e os aplicativos do festival para navegação.', 'src/img/imagem-1788924254213.jpg', 'Wed Sep 09 2026 00:24:14 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (35, 'Ao se preparar para uma prova importante, vestibular ou processo seletivo concorrido, qual é o seu principal método para absorver e fixar os conteúdos?', 'Respeito os ritmos do meu cérebro: intercalo blocos de concentração com pausas ativas para caminhar, bebo bastante água e evito noites em claro para preservar a consolidação da memória.', 'Estruturo um cronograma com metas quantitativas: resolvo bancos de exercícios calculando a porcentagem de acertos por tema e mantenho gráficos do rendimento semanal.', 'Monto grupos de estudos para debater temas em conjunto, uso a técnica de ensinar a matéria com minhas próprias palavras para os colegas e crio histórias para contextualizar os conceitos.', 'Uso aplicativos de repetição espaçada com flashcards digitais, resumo matérias usando inteligência artificial e organizo mapas mentais sincronizados na nuvem em múltiplos dispositivos.', 'src/img/imagem-1788924398872.jpg', 'Wed Sep 09 2026 00:26:38 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (36, 'Ao fazer as compras mensais de supermercado, qual hábito melhor descreve o seu comportamento no corredor e no caixa?', 'Leio com atenção a tabela nutricional e a lista de ingredientes, evitando ultraprocessados, conservantes artificiais e produtos de procedência duvidosa.', 'Comparo o valor por quilo/litro entre embalagens de tamanhos diferentes e confiro o cupom fiscal item por item para garantir que não houve cobrança incorreta.', 'Priorizo marcas que apoiam cooperativas locais ou pequenos produtores e trato os repositores e caixas com simpatia, valorizando o contato humano.', 'Utilizo aplicativos de supermercado com cupons digitais automáticos, pago por aproximação ou carteira digital e uso scanners móveis para checar preços.', 'src/img/imagem-1788948806039.jpg', 'Wed Sep 09 2026 07:13:26 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (37, 'Você precisa comprar um presente de aniversário para um amigo próximo, mas está em dúvida sobre o que escolher. Como decide?', 'Escolho algo voltado à saúde ou autocuidado, como uma cesta de chás orgânicos, óleos naturais ou um item ergonômico para a rotina dele.', 'Estipulo um orçamento limite exato e pesquiso itens cuja durabilidade e funcionalidade compensem cada centavo investido com base em comparações de preço.', 'Busco algo com significado afetivo profundo, como um álbum com memórias da amizade, uma carta sincera ou um livro marcante para a trajetória dele.', 'Presenteio com um acessório tecnológico, fones sem fio modernos, itens para o setup dele ou uma assinatura de um serviço digital inovador.', 'src/img/imagem-1788948985708.jpg', 'Wed Sep 09 2026 07:16:25 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (38, 'Em um dia livre no fim de semana, você e seus amigos decidem se reunir para jogar jogos de tabuleiro ou cartas. Qual é a sua atitude durante a partida?', 'Fico atento à postura e ao bem-estar do grupo, garantindo que o ambiente esteja arejado e que haja água e petiscos nutritivos por perto.', 'Foco na estratégia matemática: calculo probabilidades de jogadas, conto pontos mentalmente e desenvolvo táticas lógicas para vencer com eficiência.', 'Preocupo-me em garantir que todos estejam se divertindo e integrados, mediando discussões e priorizando as boas risadas acima do placar final.', 'Sugiro jogos que integrem aplicativos no celular, mecânicas digitais complementares ou componentes com design técnico e futurista.', 'src/img/imagem-1788949286260.jpg', 'Wed Sep 09 2026 07:21:26 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (39, 'Você está prestes a embarcar em uma viagem de avião que durará várias horas. Qual é o seu principal cuidado antes e durante o voo?', 'Bebo bastante água para combater o ar seco da cabine, uso roupas confortáveis e faço exercícios de circulação nas pernas para evitar fadiga corporal.', 'Calculo o peso exato da bagagem para não pagar taxas extras e cronometro os horários de check-in, raio-X e portão de embarque com antecedência precisa.', 'Observo as pessoas ao redor, converso amigavelmente com quem está próximo e reflito sobre a cultura e a história do lugar de destino.', 'Baixo previamente episódios e mídias offline no tablet, levo adaptadores e baterias portáteis e acompanho o trajeto em tempo real no mapa de voo.', 'src/img/imagem-1788949495362.jpg', 'Wed Sep 09 2026 07:24:55 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (40, 'Você notou que há sobras de alimentos e verduras quase passando do ponto na geladeira. O que faz para resolver?', 'Avalio o estado biológico dos itens para garantir frescor e crio uma receita nutritiva aproveitando talos, cascas e folhas sem perder vitaminas.', 'Analiso as porções que sobraram, calculo o rendimento de novas refeições para a semana e meço a economia gerada ao evitar qualquer tipo de desperdício.', 'reparo um prato caseiro e farto para dividir com quem mora comigo ou com vizinhos, transformando a refeição em um gesto de cuidado e acolhimento.', 'Consulto aplicativos de inteligência artificial culinária, digitando os ingredientes disponíveis para receber o passo a passo instantâneo de preparo.', 'src/img/imagem-1788949841149.jpg', 'Wed Sep 09 2026 07:30:41 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (41, 'Você comprou uma estante ou escrivaninha desmontada pela internet. Como você conduz a montagem?', 'Garanto uma boa iluminação natural, uso luvas de proteção e cuido da postura ao abaixar e levantar caixas para não forçar a lombar.', 'Separo parafusos, cavilhas e ferragens em potes numerados, conferindo item por item no manual e alinhando réguas e esquadros com exatidão.', 'Chamo amigos ou familiares para transformar a montagem em um momento descontraído de parceria, dividindo as tarefas de forma leve.', 'Busco vídeos de montagem rápida do modelo exato na internet ou uso simuladores em 3D e parafusadeiras elétricas automáticas com regulagem de torque.', 'src/img/imagem-1788950191350.jpg', 'Wed Sep 09 2026 07:36:31 GMT-0300 (Horário Padrão de Brasília)');
INSERT INTO `questoes` (`id`, `questao`, `opcaoA`, `opcaoB`, `opcaoC`, `opcaoD`, `imagem`, `created_at`) VALUES (42, 'Você decide fazer uma limpeza profunda e organização nos armários e gavetas de casa. Qual é a sua prioridade?', 'Higienizar com produtos neutros para eliminar poeira, mofo e ácaros que possam irritar as vias respiratórias e a pele da família.', 'Contar e categorizar as peças, medir o volume livre que foi ganho nas prateleiras e estimar quanto pode ser economizado ou arrecadado com desapegos.', 'Separar roupas e sapatos em bom estado para doação a quem precisa, lembrando das histórias de cada peça e compartilhando boas lembranças.', 'Organizar tudo com organizadores modulares impressos em 3D, rotulando caixas com códigos digitais ou etiquetas inteligentes no celular.', 'src/img/imagem-1788950453129.jpg', 'Wed Sep 09 2026 07:40:53 GMT-0300 (Horário Padrão de Brasília)');

--
-- Índices para tabelas despejadas
--

--
-- Índices de tabela `cadastro`
--
ALTER TABLE `cadastro`
  ADD PRIMARY KEY (`id`);

--
-- Índices de tabela `questoes`
--
ALTER TABLE `questoes`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT para tabelas despejadas
--

--
-- AUTO_INCREMENT de tabela `cadastro`
--
ALTER TABLE `cadastro`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;

--
-- AUTO_INCREMENT de tabela `questoes`
--
ALTER TABLE `questoes`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=32;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;